### ISSUE TITLE
Implement HEAD HTTP Method

### ISSUE THREAD

**Issue by daniel-lucio** [SiaFoundation/renterd#1010]
### Description

Please implement the HEAD method, I know you can pull metadata with an API endpoint, but the HTTP logic says that HEAD is the right way to do it.

### Version

v1.0.5

### What operating system are you running (e.g. Ubuntu 22.04, macOS, Windows 11)?

Mageia 9

### Anything else?

curl -X HEAD -I   'http://:XXXXX@192.168.86.34:9980/api/worker/objects/text-files/?bucket=default' 

should return the info from this endpoint (in HTTP protocol format of course)

curl -u ':xxxxxx' 'http://192.168.86.34:9980/api/bus/objects/text-files/?bucket=default'
{
        "hasMore": false,
        "entries": [
                {
                        "eTag": "9c623c85b965b4cdfed28697a26627aeea638d2e1df244d75b88e5620454c6bc",
                        "health": 1,
                        "modTime": "2024-02-28T02:15:57.300902168Z",
                        "name": "/text-files/n.txt",
                        "size": 3895,
                        "mimeType": "text/plain; charset=utf-8"
                }
        ]
}

**Comment by ChrisSchinnerl** [comment]
We can add a HEAD response but it would only be able to contain metadata for individual files you request. So a single entry, not an array of them.

**Comment by daniel-lucio** [comment]
Yes, a single object is enough.
