### ISSUE TITLE
Provide a clear way for users to back up their nodes

### ISSUE THREAD

**Issue by ChrisSchinnerl** [SiaFoundation/renterd#1033]
We should have a clear way to back up and restore the renter. Both SQLite as well as MySQL renterd.
For that we need to perform backups and restore them. 

Initially it's probably enough to do offline backups with renterd shutting down.  Once we have that documented we can think about extending the documentation with live backups.

**Comment by mike76-dev** [comment]
This works for me to do live backups of certain tables in MySQL:
```
mysqldump --single-transaction --no-tablespaces -u <DB_USER> --password=<DB_PASSWORD> <DB_NAME> [<TABLE_NAME>...] > backup.sql
```

**Comment by daniel-lucio** [comment]
Is there any documentation on how to use MySQL instead SQlite?

**Comment by artur9010** [comment]
> Is there any documentation on how to use MySQL instead SQlite?

I haven't seen anything about using mysql in docs, but all you need are five envs -https://github.com/artur9010/charts/blob/master/renterd/templates/secrets/renterd-bus-env.yaml#L9-L13
