### ISSUE TITLE
"EA account refill failed" when sufficient funds present

### ISSUE THREAD

**Issue by lukehmcc** [SiaFoundation/renterd#1045]
### Current Behavior

If you set up your renting parameters and have your node synced but funds are not yet confirmed, auto-pilot tries to form contracts and fund ephemeral accounts. This fails and spams your logs as so:
![image](https://github.com/SiaFoundation/renterd/assets/58121030/ca96d4ee-763b-4b39-a0ac-c04d07259425)

### Expected Behavior

`renterd` should wait until funds are confirmed to try to move funds around.

### Steps to Reproduce

1. Install `renterd`
2. Sync consensus
3. Set renting parameters
4. Fund your account

Generally people won't run into this issue as it takes a really long time to sync a node, but especially in a future where poor sync times are addressed this could be annoying for users.

### Version

v1.0.5

### What operating system did the problem occur on (e.g. Ubuntu 22.04, macOS 12.0, Windows 11)?

Debain 12

### Autopilot Config

{ 	"contracts": { 		"set": "autopilot", 		"amount": 50, 		"allowance": "17696317800000000000000000", 		"period": 6048, 		"renewWindow": 2016, 		"download": 14000000000, 		"upload": 14000000000, 		"storage": 10000000000, 		"prune": false 	}, 	"hosts": { 		"allowRedundantIPs": false, 		"maxDowntimeHours": 336, 		"minRecentScanFailures": 10, 		"scoreOverrides": null 	} }

### Bus Config

{ 	"default": "autopilot" } { 	"hostBlockHeightLeeway": 6, 	"maxContractPrice": "1000000000000000000000000", 	"maxDownloadPrice": "567337822000000000000000000", 	"maxRPCPrice": "1000000000000000000000", 	"maxStoragePrice": "41373151775", 	"maxUploadPrice": "53496277000000000000000000", 	"migrationSurchargeMultiplier": 10, 	"minAccountExpiry": 86400000000000, 	"minMaxCollateral": "10000000000000000000000000", 	"minMaxEphemeralAccountBalance": "1000000000000000000000000", 	"minPriceTableValidity": 300000000000 } { 	"minShards": 10, 	"totalShards": 30 } { 	"enabled": true, 	"slabBufferMaxSizeSoft": 4294967296 }

### Contract Set Contracts

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current                                  Dload  Upload   Total   Spent    Left  Speed 100 37581    0 37581    0     0  3792k      0 --:--:-- --:--:-- --:--:-- 4077k 47

**Comment by n8maninger** [comment]
What is the actual error for the account refill? This is unlikely to be related to unconfirmed funds

**Comment by lukehmcc** [comment]
> What is the actual error for the account refill? You can see it by clicking the dropdown arrow next to "error". It's unlikely to be related to unconfirmed funds. The EA alerts in general are too spammy (#1044)

`failed to fund account: couldn't fund account: insufficient funds to fund account: 0 H <= 1 H`
I have 2KS in my account right now.

**Comment by lukehmcc** [comment]
I updated the title of the thread to be more accurate.

**Comment by ChrisSchinnerl** [comment]
The error indicates that your contract doesn't have enough funds left, not your wallet. This should resolve itself as soon as the contract gets refreshed. We will update the alerts in the meantime to be less spammy.
