### ISSUE TITLE
Host scans fail due to closed streams on our side

### ISSUE THREAD

**Issue by peterjan** [SiaFoundation/renterd#1088]
```
{"level":"debug","date":"2024-03-20T17:44:42Z","component":"worker.worker","msg":"failed to scan host","host":"ed25519:018a4205dcfab9697c229c009b5bbd32f59bf2a816c09afb154b78cada60135c","hostIP":"sia-rr.synology.me:9982","timeout":10,"elapsed":6.03190447,"error":"failed to fetch host price table: PriceTable: couldn't read RPCUpdatePriceTableResponse: ReadResponse: transport error: 'stream was gracefully closed'"}
```

This one is causing contract flip-flops on `arequipa`. I know we scan twice but what's a little odd is that if you look at the logs you'll see sometimes this error is followed by "succeeded on second try", but often times it is not _and_ in those cases I think we should probably see the error twice.

In any case I think we should slightly tweak the logs and maybe handle stream closes in particular, I think we should also consider logging the first error as well. We probably didn't do that to avoid unnecessary logging but it would be nice to log the first error if the second attempt fails.

**Comment by ChrisSchinnerl** [comment]
Is it because they are timing out after 10 seconds?
