### ISSUE TITLE
Contract Formations fail due to low fees

### ISSUE THREAD

**Issue by peterjan** [SiaFoundation/renterd#1092]
```
contract formation failed, err: couldn't form contract: FormContract: ReadResponse: communication error: rejected for including too few transaction fees
```
Happens on testnet quite frequently for me. Definitely something we should tackle I think, kind of a lame reason for a contract formation to fail.

**Comment by mike76-dev** [comment]
Seen it, too, also on the mainnet.

**Comment by ChrisSchinnerl** [comment]
This should resolve itself once we use rhpv4 for forming contracts. rhpv2 doesn't have a pricetable containing the expected fees of the host.
