### ISSUE TITLE
Support for default configuration

### ISSUE THREAD

**Issue by pcfreak30** [SiaFoundation/renterd#1105]
### Description

I believe there should be the ability for a CLI flag to enable a default config mode (create the config file) instead of prompting, and also support via ENV.

I am setting up new testing renter infra for lume and have found in the process of using the docker image:

- It did a constant reboot asking for an API password
- Even if it got passed that, it would not generate a seed automatically?

I know that a lot of the current config options will be used internally for the desktop wrapper, so to support more server use cases or even just spinning up for testing in container setups, I would like the behavior to generate a config with:

- Sane defaults
- API key auto-generation
- Seed auto-generation

And put it all behind a flag/env var to be opt-in. After, update the docker entrypoint script to use this.

It makes sense for things to be interactive for hobbyist power users, but this does not work well with a docker setup with no pre-existing config created.

### Version

n/a

### What operating system are you running (e.g. Ubuntu 22.04, macOS, Windows 11)?

Ubuntu 22.04

**Comment by n8maninger** [comment]
Is this somehow different from `renterd config`? The default config already has relatively sane values. You can even generate the config using a docker container before starting the actual service container:
```sh
docker run --rm -it -v $(PWD):/data -w /data ghcr.io/siafoundation/renterd:latest config
```

If you mean completely user input free seed generation, that's a non-starter for any of our apps, imo. Generating a seed with no user input/verification, saving it to a config file somewhere, and running the service is an accident waiting to happen. If you're setting up `renterd` as infra, it's not too bad to generate a config somewhere and copy it wherever necessary.

**Comment by pcfreak30** [comment]
Understood. I did not view this from a security POV on the secrets.

I think the real crux is that I'm using docker-compose right now on a new VPS, and just launching the containers it has assumed user interaction. That and I wasn't aware of the `config` scaffold command. I do think it might make sense still to have some sort of empty config template be created on the docker setup, excluding any secret/password generation, or at a minimum have skunk_ink add the docker commands to easily reference for getting things configured.

Overall... I get your point, thanks.

**Comment by n8maninger** [comment]
Cool, I think the best fix is adding docker/compose setup guides to our docs -- @skunk-ink.

@ChrisSchinnerl -- `hostd` has an `-env` flag that disables stdin and shows an error message to create a config file specifically for Docker. I thought we had one in `renterd` too, but maybe it got lost?

**Comment by ChrisSchinnerl** [comment]
I'm not sure we ever had that in `renterd` but we can add it.

https://github.com/SiaFoundation/renterd/pull/1139
