### ISSUE TITLE
Remove GORM from codebase

### ISSUE THREAD

**Issue by ChrisSchinnerl** [SiaFoundation/renterd#1134]
This probably won't be done with a single PR but I think we might be able to get rid of GORM in small steps if we replace one method after another with the standard `sql` driver.

The goal is to create `stores/sql/sqlite` and `stores/sql/mysql` sub-packages with implementations for a common low-level interface to use in `stores`.

Tasks

- [x] Replace gormigrate
- [x] Remove GORM from production code
- [x] Remove GORM from testing

**Comment by peterjan** [comment]
done
