### ISSUE TITLE
Don't allow cluster setups without SSL by default

### ISSUE THREAD

**Issue by ChrisSchinnerl** [SiaFoundation/renterd#1135]
When running `renterd` in cluster mode it is desirable to have the traffic between workers, autopilot and bus be encrypted.
The following changes should be made to make this more obvious to users.

1. Unless connecting on localhost, `https://` should be required.
2. A new option `DisableSSL` should be added
3. `renterd` should print a helpful message on how to disable ssl in case that's what the user wants

**Comment by ChrisSchinnerl** [comment]
@n8maninger any thoughts on this? I'm a bit torn on whether we need this or if we just leave it up to the developer to know what they do.

**Comment by n8maninger** [comment]
I'd lean towards leaving it up to the developer
