### ISSUE TITLE
UI shows 404 page when following link or refreshing page

### ISSUE THREAD

**Issue by ChrisSchinnerl** [SiaFoundation/renterd#1140]
e.g. the following path exists but the link doesn't work

https://arequipa.sia.tech/buckets/default/files

**Comment by alexfreska** [comment]
This is a dupe of https://github.com/SiaFoundation/renterd/issues/1026 and is fixed by https://github.com/SiaFoundation/web/pull/537. It is in the next release: https://github.com/SiaFoundation/web/pull/531.
