### ISSUE TITLE
Add prometheus - style encoding to renterd endpoints

### ISSUE THREAD

**Issue by ChrisSchinnerl** [SiaFoundation/renterd#1190]
Since https://github.com/SiaFoundation/renterd/pull/1068 was closed we might want to address this in a new PR. We will probably need to update jap with support for introducing a `writeResponse` helper first.

**Comment by pcfreak30** [comment]
@ChrisSchinnerl this can probably be marked as done b/c of #1525 unless im missing something.

**Comment by ChrisSchinnerl** [comment]
👍
