### ISSUE TITLE
Synology HyperBackup S3 backups integration

### ISSUE THREAD

**Issue by capusta** [SiaFoundation/renterd#1210]
### Description

[Synology HyperBackup](https://www.synology.com/en-us/releaseNote/HyperBackup) (allegedly) supports S3 backups to "the cloud".  It would be very helpful to have Sia S3 integration being handled at the API level.  Would it be possible to do ?

![image](https://github.com/SiaFoundation/renterd/assets/2278098/147ddc74-d23b-4d06-9bd2-29ff3cd87808)

Other than tcpdump provided in the screenshot  - the synology client implementation remains closed source, unfortunately.  

Sia is running in a docker container on the same host.

### Version

v1.0.7 beta3

### What operating system are you running (e.g. Ubuntu 22.04, macOS, Windows 11)?

Custom (Synology OS => DSM)

### Anything else?

- https://www.synology.com/en-us/releaseNote/HyperBackup
- https://community.synology.com/enu/forum/1/post/130151

**Comment by capusta** [comment]
The buckets in Sia have certainly been created.  The issue is that Synology S3 service first tries to populate ALL the buckets in the dropdown menu (shown in red, from the screenshot above).  And it is having the issue of not finding any.  `renterd` shows no logs of the event.  400 error still persists.  using the renterd.yml and disabling authentication via `disableAuth: true` also does not seem to do anything.

Typically during Amazon S3 configuration the bucket names are populated on the dropdown menu - so the user is allowed to choose one particular bucket.

```
 # curl -u :$MYPASS localhost:9980/api/bus/buckets                              
[                                                                                
        {                                                                        
                "createdAt": "2024-01-21T17:05:12.033935422Z",                   
                "name": "default",                                               
                "policy": {                                                      
                        "publicReadAccess": false                                
                }                                                                
        },                                                                       
        {                                                                        
                "createdAt": "2024-02-09T01:26:03.285140261Z",                   
                "name": "test",                                                  
                "policy": {                                                      
                        "publicReadAccess": true                                 
                }                                                                
        },                                                                       
        {                                                                        
                "createdAt": "2024-02-09T04:22:37.615842882Z",                   
                "name": "test-two",                                                   
                "policy": {                                                      
                        "publicReadAccess": false                                
                }                                                                
        },                                                    
```

<img width="644" alt="image" src="https://github.com/SiaFoundation/renterd/assets/2278098/fdbab22b-bea3-4a41-bbdb-eb12bde459ab">

**Comment by ChrisSchinnerl** [comment]
You could try to increase the log level to `debug` to see if `renterd` starts printing some useful information. Have you been able to access `renterd` via its S3 API through a different tool like `rclone` to rule out it's a Synology HyperBackup specific issue?

**Comment by jwaspi** [comment]
I am having the same issue. My setup is similar except for `renterd` (v1.0.7 latest) running on separate host. `rclone` works successfully so I would have to imagine this issue is specific to Synology HyperBackup. I will try and gather additional logs, but I at least wanted to send a quick comment to share my findings.

**Comment by jwaspi** [comment]
It seems Synology Hyper Backup will only talk to S3 over an encrypted connection. So this is what I did as a workaround.

Synology > Control Panel > Login Portal > Advanced > Reverse Proxy > Made the below entry

![1](https://github.com/SiaFoundation/renterd/assets/46423418/c2841e69-d4e2-4069-8a7e-9004e36831a4)

A local DNS entry was made for the hostname specified in the reverse proxy and pointed to the Synology's IP address. In my case I did this in OPNsense.

![2](https://github.com/SiaFoundation/renterd/assets/46423418/62a27134-3d44-419c-9662-6c6838e2efda)

I then created the S3 destination in Hyper Backup, the only way I could get it to work was via Path-Style.

![3](https://github.com/SiaFoundation/renterd/assets/46423418/36638e59-0593-4da6-a493-0b72eaaf7d85)

Hope this helps.

**Comment by ChrisSchinnerl** [comment]
Thanks for doing that research! Interesting that it doesn't like "unsafe" connections but doesn't really tell you.
You might be able to get it to work without path style if you set `RENTERD_S3_HOST_BUCKET_ENABLED` or the corresponding yaml config option in `renterd`. 

Closing this since it appears to be fixed with additional configuration.

**Comment by capusta** [comment]
confirmed working ... thanks reverse proxy :) 
Enabling renterd_s3_host_bucket also seems to break the implementation ... it does not see any buckets upon the initial connection.
![image](https://github.com/SiaFoundation/renterd/assets/2278098/07c951f4-d317-43a0-9eac-281549440ac1)
