### ISSUE TITLE
`current_period` isn't recalculated upon restart

### ISSUE THREAD

**Issue by mike76-dev** [SiaFoundation/renterd#1215]
### Current Behavior

After not having started `renterd` for a few months, I found out that the contracts are not formed because "the end height is in the past". After digging into the issue, it turned out that `current_period` in the `autopilots` table still contained the value from the past, when I last started `renterd`.

### Expected Behavior

Current Period should be recalculated every time `renterd` starts.

### Version

Latest `master` merged into a custom fork

### What operating system did the problem occur on (e.g. Ubuntu 22.04, macOS 12.0, Windows 11)?

Ubuntu 22.04

### Autopilot Config

Not relevant

### Bus Config

Not relevant

### Contract Set Contracts

Not relevant

**Comment by ChrisSchinnerl** [comment]
In theory it should update but you are right it would not happen immediately upon being synced again. Instead it would probably update the current period by 1 period every 30 minutes.
