### ISSUE TITLE
Help: Debugging currency components

### ISSUE THREAD

**Issue by pcfreak30** [SiaFoundation/renterd#1221]
### Current Behavior

I am doing debugging atm and testing the js currency components. Ive compared them to the output from my go code and minus some very miniscule rounding (at like 20 decimal places), things seem to add up. I have also taken the current sc rate renterd is pulling from siacentral to compare to what the ui is doing.

See https://gist.github.com/pcfreak30/92eee34d30f7a46ca10bf9022a769b7a

I have 1 question and 1 concern:

Question:

How do I get a console.log of the sc amount at the end, because im getting 0, regardless of any number i pass to toString.

Concern:

I am seeing possible inaccuracies on how things are being computed in the UI, or im definitely making a mistake somewhere. Everything looks right broken down to byte per block, but the UI shows a bit different when thats taken back and reconstructed? There is also the fact that renterd seems to truncate the max sc storage number in hastings (in api and in the settings table json data) after a certain decimal point?

Kudos.

### Expected Behavior

n/a

### Version

26cc954

### What operating system did the problem occur on (e.g. Ubuntu 22.04, macOS 12.0, Windows 11)?

Ubuntu

### Autopilot Config

n/a

### Bus Config

n/a

### Contract Set Contracts

n/a

**Comment by alexfreska** [comment]
//const avgSCRate = new BigNumber("0.009598540503976240011111");
const avgSCRate = new BigNumber("0.007160071032");
const maxPrice = new BigNumber(5);
let storagePrice = maxPrice.div(avgSCRate);
console.log("after rate", storagePrice.toString());
storagePrice = storagePrice.div(3);
console.log("after redundancy",storagePrice.toString());
storagePrice = storagePrice.div(TiBToBytes(1));
console.log("after tb",storagePrice.toString());
storagePrice = storagePrice.div(monthsToBlocks(1));
console.log("after blocks",storagePrice.toString());
console.log(toSiacoins(storagePrice, scDecimalPlaces).toString());

**Comment by alexfreska** [comment]
@pcfreak30 to match the UI:
```diff
const avgSCRate = new BigNumber("0.007160071032");
const maxPrice = new BigNumber(5);
let storagePrice = maxPrice.div(avgSCRate);
console.log("after rate", storagePrice.toString());

// Remove redundancy division, the UI does not include redundancy, see screenshot below.
- storagePrice = storagePrice.div(3);
- console.log("after redundancy",storagePrice.toString());

// The UI uses TB not TiB
- storagePrice = storagePrice.div(TiBToBytes(1));
+ storagePrice = storagePrice.div(TBToBytes(1));

console.log("after tb",storagePrice.toString());
storagePrice = storagePrice.div(monthsToBlocks(1));
console.log("after blocks",storagePrice.toString());

// toSiacoins converts hastings to siacoins, you are already operating on siacoins
- console.log(toSiacoins(storagePrice, scDecimalPlaces).toString());
+ console.log(storagePrice.toString());
// equals: 0.00000000000016164747559551968 SC

// If you want hastings you can do:
+ console.log(toHastings(storagePrice).toString());
// equals: 161647475596 H
```
