### ISSUE TITLE
Debug Report Feature

### ISSUE THREAD

**Issue by pcfreak30** [SiaFoundation/renterd#1279]
### Description

I recently realized that end users of renterd may have problems with getting the right settings for uploading, despite all the UI help, or if they get it working, might have bad hosts/slow ones.

In the renterd git repo currently, you have as part of the new bug report issue template:

```
curl -u ":[YOUR_PASSWORD]" http://localhost:9980/api/autopilot/config

curl -u ":[YOUR_PASSWORD]" http://localhost:9980/api/bus/setting/contractset
curl -u ":[YOUR_PASSWORD]" http://localhost:9980/api/bus/setting/gouging
curl -u ":[YOUR_PASSWORD]" http://localhost:9980/api/bus/setting/redundancy
curl -u ":[YOUR_PASSWORD]" http://localhost:9980/api/bus/setting/uploadpacking

curl -u ":[YOUR_PASSWORD]" "http://localhost:9980/api/bus/contracts?contractset=autopilot" | grep '"id"' | wc -l
```

What I feel will be a massive value add and to reduce on confusion or problems with community support requests in getting renterd configuration issues solved, is a UI tool that creates a report, possibly even using markdown (or maybe just formatted json combining everything), with the outputs of everything possibly needed so it can be shared as a gist/pastebin or similar for technical troubleshooting and make tracking any real possible problems a no-brainer longer term.

### Version

n/a

### What operating system are you running (e.g. Ubuntu 22.04, macOS, Windows 11)?

n/a

**Comment by ChrisSchinnerl** [comment]
I feel like that was planned already but I can't find the issue^^

**Comment by alexfreska** [comment]
More context, we can close both when complete: https://github.com/SiaFoundation/renterd/issues/1119
