### ISSUE TITLE
table slices in db land has postgresql keyword 'offset' as a column name.

### ISSUE THREAD

**Issue by toddfries** [SiaFoundation/renterd#1326]
### Current Behavior

While this can be worked around by quoting the column name, best practice is to not do that.
Consider renaming the field to be slice_offset or slab_offset ?
I can do the work if you point me in the direction you want this to go. ;-)

### Expected Behavior

foo=# CREATE TABLE slices (
foo(#   id SERIAL PRIMARY KEY,
foo(#   created_at timestamp DEFAULT NULL,
foo(#   db_object_id int DEFAULT NULL,
foo(#   object_index int DEFAULT NULL,
foo(#   db_multipart_part_id int DEFAULT NULL,
foo(#   db_slab_id int DEFAULT NULL,
foo(#   "offset" int DEFAULT NULL,
foo(#   length int DEFAULT NULL,
foo(#   CONSTRAINT fk_multipart_parts_slabs FOREIGN KEY (db_multipart_part_id) REFERENCES multipart_parts (id) ON DELETE CASCADE,
foo(#   CONSTRAINT fk_objects_slabs FOREIGN KEY (db_object_id) REFERENCES objects (id) ON DELETE CASCADE,
foo(#   CONSTRAINT fk_slabs_slices FOREIGN KEY (db_slab_id) REFERENCES slabs (id)
foo(# );
... I can do this workaround, but .. 

### Steps to Reproduce

foo=# CREATE TABLE slices (
foo(#   id SERIAL PRIMARY KEY,
foo(#   created_at timestamp DEFAULT NULL,
foo(#   db_object_id int DEFAULT NULL,
foo(#   object_index int DEFAULT NULL,
foo(#   db_multipart_part_id int DEFAULT NULL,
foo(#   db_slab_id int DEFAULT NULL,
foo(#   offset int DEFAULT NULL,
foo(#   length int DEFAULT NULL,
foo(#   CONSTRAINT fk_multipart_parts_slabs FOREIGN KEY (db_multipart_part_id) REFERENCES multipart_parts (id) ON DELETE CASCADE,
foo(#   CONSTRAINT fk_objects_slabs FOREIGN KEY (db_object_id) REFERENCES objects (id) ON DELETE CASCADE,
foo(#   CONSTRAINT fk_slabs_slices FOREIGN KEY (db_slab_id) REFERENCES slabs (id)
foo(# );
ERROR:  syntax error at or near "offset"
LINE 8:   offset int DEFAULT NULL,
          ^

### Version

v1.0.7-beta.2-292-gb447afc6

### What operating system did the problem occur on (e.g. Ubuntu 22.04, macOS 12.0, Windows 11)?

Debian 12.5

### Autopilot Config

{         "contracts": {                 "set": "autopilot",                 "amount": 12,                 "allowance": "21466666666666666666666666667",                 "period": 2016,                 "renewWindow": 2016,                 "download": 933333333333,                 "upload": 4666666666667,                 "storage": 10000000000000,                 "prune": true         },         "hosts": {                 "allowRedundantIPs": true,                 "maxDowntimeHours": 672,                 "minProtocolVersion": "1.6.0",                 "minRecentScanFailures": 30,                 "scoreOverrides": null         } }

### Bus Config

{         "default": "autopilot" } {         "hostBlockHeightLeeway": 20,         "maxContractPrice": "15000000000000000000000000",         "maxDownloadPrice": "3000000000000000000000000000",         "maxRPCPrice": "1000000000000000000000",         "maxStoragePrice": "231481481481",         "maxUploadPrice": "1000000000000000000000000000",         "migrationSurchargeMultiplier": 2,         "minAccountExpiry": 86400000000000,         "minMaxEphemeralAccountBalance": "1000000000000000000000000",         "minPriceTableValidity": 60000000000 } {         "minShards": 2,         "totalShards": 4 } {         "enabled": true,         "slabBufferMaxSizeSoft": 4294967296 }

### Contract Set Contracts

      12

### Anything else?

I know this is not a bug in existing code but someone at some point when trying postgresql will discover this.
Consider this a crystal ball view of the future, we can prepare for it now. ;-)

**Comment by n8maninger** [comment]
Postgres will have a distinct driver and schema. We’re not too concerned about this in the context of the current gorm schema.
