### ISSUE TITLE
Object constraint sql failed

### ISSUE THREAD

**Issue by pcfreak30** [SiaFoundation/renterd#1329]
### Current Behavior

```{"level":"error","ts":"2024-06-23T22:23:20Z","logger":"SQL","caller":"gorm@v1.25.9/finisher_api.go:651","msg":"trace","error":"NOT NULL constraint failed: objects.db_directory_id","elapsed":"1.359491ms","rows":0,"sql":"INSERT INTO `objects` (`created_at`,`db_bucket_id`,`object_id`,`key`,`health`,`size`,`mime_type`,`etag`) VALUES (\"2024-06-23 22:23:20.448\",3,\"/H6WJSuIJeqyevUHbWke4weQoPSbd1e1PrkP08BhHUyhL.obao\",\"<binary>\",1,10184,\"application/octet-stream\",\"b661d19cd4ffbe55362b5468ae0d2aff\") RETURNING `id`","stacktrace":"gorm.io/gorm.(*DB).Transaction\n\tgorm.io/gorm@v1.25.9/finisher_api.go:651\ngo.sia.tech/renterd/stores.(*SQLStore).retryTransaction\n\tgo.sia.tech/renterd/stores/sql.go:574\ngo.sia.tech/renterd/stores.(*SQLStore).UpdateObject\n\tgo.sia.tech/renterd/stores/metadata.go:1746\ngo.sia.tech/renterd/bus.(*bus).objectsHandlerPUT\n\tgo.sia.tech/renterd/bus/bus.go:1280\ngo.sia.tech/jape.Mux.adaptor.func3\n\tgo.sia.tech/jape@v0.11.2-0.20240124024603-93559895d640/server.go:164\ngithub.com/julienschmidt/httprouter.(*Router).ServeHTTP\n\tgithub.com/julienschmidt/httprouter@v1.3.0/router.go:387\nmain.main.main.BasicAuth.func6.func7\n\tgo.sia.tech/jape@v0.11.2-0.20240124024603-93559895d640/server.go:222\nnet/http.HandlerFunc.ServeHTTP\n\tnet/http/server.go:2166\nmain.treeMux.ServeHTTP\n\tgo.sia.tech/renterd/cmd/renterd/web.go:28\nmain.treeMux.ServeHTTP\n\tgo.sia.tech/renterd/cmd/renterd/web.go:23\nnet/http.serverHandler.ServeHTTP\n\tnet/http/server.go:3137\nnet/http.(*conn).serve\n\tnet/http/server.go:2039"}
{"level":"warn","ts":"2024-06-23T22:23:20Z","logger":"sql","caller":"stores/sql.go:587","msg":"transaction attempt 6/7 failed, retry in 10s,  err: failed to create object: NOT NULL constraint failed: objects.db_directory_id"}```

I have taken a backup of the database as well since the cause of getting the db in this state is unclear.

### Expected Behavior

file to upload

### Version

7e6dcd5

### What operating system did the problem occur on (e.g. Ubuntu 22.04, macOS 12.0, Windows 11)?

Ubuntu

### Autopilot Config

n/a

### Bus Config

n/a

### Contract Set Contracts

n/a

**Comment by ChrisSchinnerl** [comment]
Looking at the commit you provided it seems like you downgraded from a version that already had the new `directories` table to `v1.0.7` which doesn't have it. `v1.0.7` won't know about it and therefore not fill the `db_directory_id` column causing the issue you are seeing.
