### ISSUE TITLE
Debug churn caused by redundant ip check

### ISSUE THREAD

**Issue by ChrisSchinnerl** [SiaFoundation/renterd#1331]
Seeing the following alert on a new node. It seems to indicate that it was forming 100 or so contracts at first and started uploading to them. Then it threw them away after more contracts were formed due to redundant IP ranges.
The big question being why would it form a contract with a host that is in conflict with an existing one in the first place.

![Image](https://github.com/SiaFoundation/renterd/assets/3903476/9187ca63-c9c6-430f-ae0c-c69ada17ef80)

**Comment by peterjan** [comment]
Fixed by contractor refactor.
