### ISSUE TITLE
Changing bucket policy undefined

### ISSUE THREAD

**Issue by n8maninger** [SiaFoundation/renterd#1349]
### Current Behavior

The modal for changing bucket policy doesn't actually change the bucket policy. It looks like it hits `/api/bus/bucket/undefined`

### Expected Behavior

Change the bucket policy.

### Version

v1.0.7

### What operating system did the problem occur on (e.g. Ubuntu 22.04, macOS 12.0, Windows 11)?

N/a

### Autopilot Config

N/a

### Bus Config

N/a

### Contract Set Contracts

N/a

**Comment by alexfreska** [comment]
Fix was merged a few weeks ago, this should be fixed on the latest beta version.

https://github.com/SiaFoundation/renterd/assets/1412796/dbc5e54b-85e9-4efd-8a90-3eae6f9a430d
