### ISSUE TITLE
Extend IP subnet check to take into account host's domain

### ISSUE THREAD

**Issue by ChrisSchinnerl** [SiaFoundation/renterd#1359]
Even with the IP range check we sometimes lose a lot of contracts at once due to hosts which are clearly on the same domain.
e.g. `foo.example.com`, `bar.example.com`, `baz.example.com`.
We should only form a contract with one of those hosts to avoid losing too much redundancy at once when a provider goes offline. 

e.g. Arequipa just lost 10 contracts at once due to such a provider no longer accepting contracts on all hosts.

**Comment by NickJH** [comment]
How are you going to cater for people using DDNS? There a many hosts using noip.com's free domains (such as ddns.net), FreeDNS, DynuDNS and so on. These hosts can safely share the some domain and are likely nothing to do with each other.

**Comment by ChrisSchinnerl** [comment]
Unfortunately we can't without making renters vulnerable. If a host doesn't have a custom domain or static IP, it will be a first come, first served situation. Similar to how hosts in the same datacenter compete already.

**Comment by NickJH** [comment]
So there are 89 ddns.net (noip.com) active hosts, 5 freedns/dnsfree, 10 hopto.org/zapto.org (noip.com), 2 sytes.net (noip.com), 36 duckdns.org and many other DDNS names. You are really going to can them? There is even a DDNS update in hostd for noip.com and duckdns.org names.

**Comment by ChrisSchinnerl** [comment]
We don't need to outright can them. The details are still not worked out but there might be less invasive ways.
e.g. if we need `n` contracts for the set we could pick as many as possible from unique domains and add more if we can't get a full set.

**Comment by NickJH** [comment]
Please can I suggest you discuss this with Nate and come up with a concrete proposal. I think it is crazy to try to pick just one domain from ddns.net when they make up over 25% of the hosts and they are randomly scattered over the internet. The original idea was to ensure geographical separation of the hosts. You may be able to build a small database of "approved" DDNS domains. But then how do you deal with your own *.sia.host domain, and who is going to be the gatekeeper? CtrlAltDefeat has 3 servers. 2 are in different towns in Holland and one is in Germanay, but you want to effectively reduce him to 1 server?

Even the /24 concept it is broken. I have a /29 block, 62.30.63.88/29 and 62.30.63.87 and 62.30.63.96, outside my subnet, are geographically nothing to do with me or my location yet they get caught by the /24 rule. Perhaps even the /24 rule should be revisited and try to do a whois to see how big the block is but I think you have to be cute as RIPE return the data differently from IANA etc.

**Comment by n8maninger** [comment]
We're already discussing, internally. I'm going to close this for now while we discuss alternatives.
