### ISSUE TITLE
ui: Can't use domain name in "Connect peer" modal

### ISSUE THREAD

**Issue by artur9010** [SiaFoundation/renterd#1361]
### Current Behavior

Currently renterd webui suggests that I can use domain name in "Connect peer" modal

![Screenshot 2024-07-02 at 17 08 06](https://github.com/SiaFoundation/renterd/assets/4835677/d4f27c85-4f41-4a4c-99e5-6f524c29134e)

but after providing domain name, it says it is incorrect ip, I've used `de5a9e88836fb1c4.sia.host:9881`

![Screenshot 2024-07-02 at 17 09 27](https://github.com/SiaFoundation/renterd/assets/4835677/3b0eca6d-b479-4f0a-9213-8373eb285162)

### Expected Behavior

x

### Steps to Reproduce

1. Go to "Blockchain node"
2. Try to add peer using domain name

### Version

b052e0c

### What operating system did the problem occur on (e.g. Ubuntu 22.04, macOS 12.0, Windows 11)?

Ubuntu 22.04, kubernetes (https://github.com/artur9010/charts/tree/master/renterd)

### Autopilot Config

probably not needed

### Bus Config

probably not needed

### Contract Set Contracts

probably not needed

**Comment by ChrisSchinnerl** [comment]
Fixed by https://github.com/SiaFoundation/coreutils/pull/67
