### ISSUE TITLE
Renterd fails to start if pinned price conversion fails

### ISSUE THREAD

**Issue by ChrisSchinnerl** [SiaFoundation/renterd#1376]
Got this error on my node. If we can't fetch a rate we should probably just keep the prices the way they are and try again later.

2024-07-11T13:20:28Z    FATAL   failed to setup bus: failed to fetch exchange rate for 'usd': unexpected status code: 525

**Comment by cmdntd** [comment]
Yes, autopilot seems not start again after uploads failed.

1. Autopilot just notifies that uploads fail by st (like size storage, not clear at price)
2. It just stops forever with 100% (not upload to network yet)
3. If I tried to upload the same (when conditions were fine), it would keep old failed one after all. This means I must delete old one to see the new one uploaded successfully, or just see both at 100% status like above.

This is not safe for files upload, speacially in case that many files unfollowed by me.
This is better if autopilot could change price on suggestion to keep uploads not failed automatically.
