### ISSUE TITLE
Health refresh frequently fails on Arequipa

### ISSUE THREAD

**Issue by ChrisSchinnerl** [SiaFoundation/renterd#1378]
The health refresh often fails after reaching the maximum number of retries we perform upon a "database is locked" error.
Sure it's a large node using SQLite but it might still be worth digging into what operation is so slow that it blocks a refresh for minutes.

![Image](https://github.com/SiaFoundation/renterd/assets/3903476/4e69dce7-3f83-4d75-a2b9-e01fa4a909e8)

**Comment by peterjan** [comment]
This hardly ever happens. In the last week it happened once on aug 13. I think we can safely close it out @ChrisSchinnerl ?
