### ISSUE TITLE
ui: add option to view migration progress

### ISSUE THREAD

**Issue by artur9010** [SiaFoundation/renterd#1381]
### Description

Currently UI displays alert about starting migration, it would be nice to have a migration progress somewhere (that would be useful for those who run renterd on their laptops once a week to know when they can safely shut it down)

<img width="1519" alt="Screenshot 2024-07-13 at 17 01 39" src="https://github.com/user-attachments/assets/1f43972e-9be1-432e-a4e6-eb3b923aa309">

### Version

0be69bc

**Comment by artur9010** [comment]
<img width="482" alt="Screenshot 2024-07-13 at 17 06 08" src="https://github.com/user-attachments/assets/b8873e6e-cc67-4a61-982f-e4fd697a5102">

i think adding a bar at top like "testnet warning" would be nice

**Comment by ChrisSchinnerl** [comment]
Closing this since the alert will now be updated as migrations progress
