### ISSUE TITLE
Contracts keep renewing, locking collateral

### ISSUE THREAD

**Issue by NickJH** [SiaFoundation/renterd#1388]
### Current Behavior

Note this is all from a hoster's perspective.

Some contracts start off and very quickly renew, presumably increasing their collateral. The keep doing this and it ends up locking up a lot of collateral. I have 3 contracts like this:

Initial contract 3fa5e6ed6ac3d793498d3a050aa0791fad0d92929059d0e4fcb5a93aeda7cf65, end block of all 484,453:

Renewal Date | Locked Collateral
-- | --
26/06/2024 | 102.949
28/06/2024 | 9.355
28/06/2024 | 139.539
29/06/2024 | 167.406
01/07/2024 | 200.877
02/07/2024 | 241.136
03/07/2024 | 289.492
05/07/2024 | 347.990
06/07/2024 | 418.039
08/07/2024 | 501.341
13/07/2024 | 598.501
20/07/2024 | 716.120

Initial contract ac286c61db1bdd4758be9eb4371b4b62aa181ccfb05d8b6b2e2f571d7454db88, end block of all contracts 483,170:

Renewal Date | Locked Collateral
-- | --
18/06/2024 | 172.544
26/06/2024 | 279.068
29/06/2024 | 452.448
02/07/2024 | 542.825
05/07/2024 | 654.122
08/07/2024 | 784.731
17/07/2024 | 932.001

Initial contract aec22caafaf2df2394c0321df3c1a9ff37ba3e649835e8f3086512c687f99662, end block of all contracts 487,569:

Renewal Date | Locked Collateral
-- | --
18/07/2024 | 30.900
19/07/2024 | 50.172
19/07/2024 | 60.177

The first and third are the worst with the quickest renewal rate. It is tying up a lot of collateral.

### Expected Behavior

I want to see less tied up in collateral so less frequent contract renewals - but this may become irrelevant after the hardfork.

### Version

Sorry, no idea as this is from a hoster's perspective

### What operating system did the problem occur on (e.g. Ubuntu 22.04, macOS 12.0, Windows 11)?

n/a

### Autopilot Config

n/a

### Bus Config

n/a

### Contract Set Contracts

n/a

### Anything else?

This was raised in discord at https://discord.com/channels/809849352516141067/827641929008152635/1257791742263169088 with a few follow-ups.

**Comment by ChrisSchinnerl** [comment]
Closing this since the renewal code was updated to not add additional funds. So the amount of locked collateral should have drastically decreased. The final fix will be the hardfork when funds will get immediately released upon renewal.
