### ISSUE TITLE
Switch networks at runtime

### ISSUE THREAD

**Issue by n8maninger** [SiaFoundation/renterd#1422]
### Description

Migrate `renterd` from separate binaries for Mainnet and Zen to a runtime config option like the other apps. This will reduce confusion of managing binaries with the same name, makes it possible for users using the Linux and Homebrew installation methods to use the testnet, simplifies the CI steps, and the Dockerfile.

**Comment by ChrisSchinnerl** [comment]
NOTE: Have to make sure using the wrong flag on an existing node returns an error instead of nuking the database
