### ISSUE TITLE
Expose internal conversion rate of pin manger through API for use in the UI

### ISSUE THREAD

**Issue by ChrisSchinnerl** [SiaFoundation/renterd#1426]
This also requires setting a default price resolver and then the UI can use the daemon's endpoint for price conversions. That way the UI and daemon always agree on conversion rates.

**Comment by n8maninger** [comment]
I'm of the opinion that the daemons should expose a configured explorer URL and whether explorer data should be used as part of `[GET] /state` instead of adding additional endpoints. There's no real difference from the UI's perspective, but it reduces maintenance surface and complexity of our API.

i.e.
```json
{
  "startTime": "2023-12-20T18:30:22.411584799Z",
  "explorer": {
    "enabled": true,
    "url": "https://api.siascan.com"
  },
  "network": "zen",
  "version": "b2fbaa8",
  "commit": "b2fbaa8",
  "os": "linux",
  "buildTime": "2023-12-20T18:13:22Z"
}
```

The configured explorer should be used consistently for all the subsystems in the daemons as well (remove the separate `forexAPIURL` field for price pinning).

**Comment by ChrisSchinnerl** [comment]
@n8maninger we don't need a new endpoint but `renterd` does have the settings endpoint that the UI uses for updating/reading settings. We could add that info to `/state` but then we just have it in 2 places.

**Comment by peterjan** [comment]
@ChrisSchinnerl we could extend our `Config` with an `Explorer` section and deprecate the field in the `pinsettings`. The alternative is that the UI fetches this URL from the `pinsettings` at the cost of being inconsistent with all of the other apps.

**Comment by ChrisSchinnerl** [comment]
Adding it to the config is a bit of a step back though since it makes the URL static. Users wouldn't be able to configure the backend to use at runtime anymore.

**Comment by peterjan** [comment]
I agree, it's just for the sake of consistency between daemons that I would consider changing it in `renterd`. Being able to configure it at runtime, along with not really understanding the need for an "explorer" section in the `renterd` config is the reason it was put there in the first place.

**Comment by n8maninger** [comment]
Most users will never change it at all. It’s not really necessary to have on the config page, it’s just bloat.
