### ISSUE TITLE
Add contract pruning endpoint to bus

### ISSUE THREAD

**Issue by ChrisSchinnerl** [SiaFoundation/renterd#1445]
After https://github.com/SiaFoundation/renterd/pull/1440 we should have everything we need in place to add the contract pruning PR to the bus. 

This should make the locking of the contract more robust since the bus can just lock the contract forever (`math.MaxUint64`) and defer the unlock within the same endpoint and in theory it allows us to compute the diff between the contract on the host with the database without loading all roots from the database. 

Essentially this is another preparation for v2 for when contracts will exclusively be handled by the bus.

**Comment by peterjan** [comment]
done https://github.com/SiaFoundation/renterd/pull/1472
