### ISSUE TITLE
pricepinning response format crashes the UI extra

### ISSUE THREAD

**Issue by alexfreska** [SiaFoundation/renterd#1448]
### Current Behavior

The UI crashes due to a response structure mismatch. This is on the latest dev branch / test nodes.

### Expected Behavior

The UI expects `autopilots.allowance`, there is an extra `autopilot` object.
<img width="760" alt="Screenshot 2024-08-15 at 12 42 59 PM" src="https://github.com/user-attachments/assets/1f8d0cdb-eadf-4451-bdb1-a75e57f940ce">

### Version

dev

### What operating system did the problem occur on (e.g. Ubuntu 22.04, macOS 12.0, Windows 11)?

macos

### Autopilot Config

-

### Bus Config

-

### Contract Set Contracts

-

**Comment by ChrisSchinnerl** [comment]
@alexfreska The second `autopilot` is the ID of the autopilot. It just so happens that we default to `autopilot` for it.
The idea being that in the future you might be able to have multiple autopilots managing multiple contract sets with different allowances. So that list could look like this
```
"autopilots": {
  "autopilot1": {
    "allowance": {...}
  }
  "autopilot2": {
    "allowance": {...}
  }
}
```
