### ISSUE TITLE
The UI does not work

### ISSUE THREAD

**Issue by aa6** [SiaFoundation/renterd#152]
When I visit http://127.0.0.1:9980/ type API password and press button "Set" I'm getting an error:
"Unexpected token '<', "<!DOCTYPE "... is not valid JSON" - in chromium
"JSON.parse: unexpected character at line 1 column 1 of the JSON data" - in firefox

**Comment by n8maninger** [comment]
The UI is just a placeholder. `renterd` is not ready for general users yet.
