### ISSUE TITLE
Populate pinned settings with configured autopilots

### ISSUE THREAD

**Issue by ChrisSchinnerl** [SiaFoundation/renterd#1532]
@ChrisSchinnerl `/bus/settings/pinned` previous returned an object for `autopilots` and a default object for the known autopilot ID similar to the gougingSettingsPins. Let me know if this is intentional or regression.
<img width="366" alt="Screenshot 2024-09-13 at 2 46 01 PM" src="https://github.com/user-attachments/assets/fe33e59c-d956-40c7-a16c-1617273a3613">

_Originally posted by @alexfreska in https://github.com/SiaFoundation/renterd/issues/1512#issuecomment-2349882238_

**Comment by peterjan** [comment]
done here https://github.com/SiaFoundation/renterd/pull/1536
