### ISSUE TITLE
Enabling price pinning in renterd 1.1.0 beta5 crashes it

### ISSUE THREAD

**Issue by artur9010** [SiaFoundation/renterd#1608]
### Current Behavior

When I go to settings and enable price pinning, renterd crashes.

crash log: https://gist.github.com/artur9010/431aca43a175399a4dc622cfdc531fc2

### Expected Behavior

do not crash

### Version

1.1.0 beta5

### What operating system did the problem occur on (e.g. Ubuntu 22.04, macOS 12.0, Windows 11)?

Fedora linux, running from binary

### Autopilot Config

{ 	"contracts": { 		"set": "autopilot", 		"amount": 50, 		"allowance": "1462047917400000000000000000", 		"period": 6048, 		"renewWindow": 2016, 		"download": 700000000000, 		"upload": 1400000000000, 		"storage": 2000000000000, 		"prune": false 	}, 	"hosts": { 		"allowRedundantIPs": false, 		"maxDowntimeHours": 336, 		"minProtocolVersion": "1.6.0", 		"maxConsecutiveScanFailures": 10, 		"scoreOverrides": null 	} }

### Bus Config

below

### Contract Set Contracts

not even synced

### Anything else?

bus config

```
{"default":"autopilot"}

{"hostBlockHeightLeeway":6,"maxContractPrice":"15000000000000000000000000","maxDownloadPrice":"3000000000000000000000000000","maxRPCPrice":"1000000000000000000000","maxStoragePrice":"694444444444","maxUploadPrice":"3000000000000000000000000000","migrationSurchargeMultiplier":10,"minAccountExpiry":86400000000000,"minMaxEphemeralAccountBalance":"1000000000000000000000000","minPriceTableValidity":300000000000}

{"minShards":10,"totalShards":30}

{"enabled":true,"slabBufferMaxSizeSoft":4294967296}
```

**Comment by ChrisSchinnerl** [comment]
@artur9010 does this happen consistently or was it a one time thing?

**Comment by artur9010** [comment]
it was probably a one time thing, i've tried it next day and it worked.
