### ISSUE TITLE
Individual Host Autopilot Scans

### ISSUE THREAD

**Issue by pcfreak30** [SiaFoundation/renterd#1649]
### Description

I am requesting an endpoint on the autopilot, potentially `/host/:pubkey/scan` that will either both run a rhp scan and update the `host_checks` table, or pull existing scan data and rank the host (meaning I can call worker rhp scan then autopilot scan).

I looked and it seems as of 9f67518242e80d9e419ddacb2a8e4950e8e37000 `autopilot/contractor/contractor.go:1098` only the contractor has the ability to do this, and its not exposed higher level outside the `PerformContractMaintenance` in `Contractor`.

Right now I am pulling in benchmark data from hostscore, but as it seems the scores only run on a full autopilot run currently, im looking at being forced to rely on it, per batch of hosts I pull in, when I only need to know if the hosts are usable and trigger a full AP scan when I have what I need.

I know a large refactor is currently being done on what runs where with the autopilot/bus, so im open to input if another route should be taken.

### Version

v1.0.8

### What operating system are you running (e.g. Ubuntu 22.04, macOS, Windows 11)?

Ubuntu

**Comment by ChrisSchinnerl** [comment]
Closing this since it will be part of https://github.com/SiaFoundation/renterd/issues/1640
