### ISSUE TITLE
Monitor expired contracts to unlock funds if host doesn't do it

### ISSUE THREAD

**Issue by ChrisSchinnerl** [SiaFoundation/renterd#1719]
A side-effect of the new consensus is the fact that a node needs to become active to unlock contract funds. Usually that happens either implicitly when renewing a contract or the host does it after a contract expires.
The renter is missing that mechanism which is important for when a host goes offline without unlocking the funds. So the renter needs to check for expired contracts in the chain subscriber and then broadcast a txn starting a while after the contract expired to give the host some time to do it first.

**Comment by NickJH** [comment]
Are you saying that, if a host has a meltdown, he no longer automatically receives back the Locked Collateral - Risked Collateral for any contract? And bandwidth income?

**Comment by ChrisSchinnerl** [comment]
> Are you saying that, if a host has a meltdown, he no longer automatically receives back the Locked Collateral - Risked Collateral for any contract? And bandwidth income?

You will need to boot up the host again after a meltdown and then it will automatically unlock the funds.

**Comment by NickJH** [comment]
And keep it running until all the contracts expire? This is a big shift. It used to be that if your host went down and was not recovered, that you just lost your risked collateral. You still got the remaining Locked collateral back and depending on something (RHP2/3?) you also got your accrued bandwidth income.

**Comment by ChrisSchinnerl** [comment]
You don't need to keep it running. Theoretically you can take it offline, come back in a year, boot it up for an hour and have it unlock your funds.  There is no deadline for unlocking funds from expired contracts. The same is true today. You need to wait for contracts to expire and then start up your node to send the funds.
