### ISSUE TITLE
contracts response is missing `hostIP` field

### ISSUE THREAD

**Issue by alexfreska** [SiaFoundation/renterd#1747]
### Current Behavior

<img width="1829" alt="Image" src="https://github.com/user-attachments/assets/0c02f7c8-8887-4d73-865a-2f0e3db25483" />

### Expected Behavior

The response used to include `hostIP` which was used for some features.

### Version

dev

### What operating system did the problem occur on (e.g. Ubuntu 22.04, macOS 12.0, Windows 11)?

macos

### Autopilot Config

-

### Bus Config

-

### Contract Set Contracts

-

**Comment by ChrisSchinnerl** [comment]
@alexfreska The contracts no longer return that field on purpose. For host information, you'll need to fetch the host using the corresponding endpoint using the public key in the contract.
