### ISSUE TITLE
Delete sectors from host_sectors 72 hours after the last update

### ISSUE THREAD

**Issue by ChrisSchinnerl** [SiaFoundation/renterd#1749]
As the title suggests, a sector from `host_sectors` should be deleted 144*3 blocks after the last time it was associated with any host which is approximately 72 hours. I left a TODO in `ArchiveContract` next to the query we had in there.

To achieve that, every time we delete from `contract_sectors`, we need to first check which sectors would become unpinned from any contract. Then we update the timestamp of these sectors before deleting from `contract_sectors`.

Afterwards we can run a query to prune all `host_sectors` that haven't been updated in 3 days AND for which there is no entry in `contract_sectors`.

We need this for 2 reasons:
1. when a sector is uploaded, it should remain in the `host_sectors` table for 72 hours so that we can use it to find sectors we still need to pin to a contract
2. when a contract is deleted from the database, we still want to be aware of the host that has the sector so that we can repair it to another contract. The particular edge case that comes to mind is the v1 to v2 transition where v1 contracts are deleted and the data is then migrated to v2 contracts. 

NOTE: we should consider taking the end height of the contract we archive into account when setting `updated_at`. Realistically, if the contract we delete has an end height that is 4 weeks in the future, we can also set `updated_at` to be 4 weeks in the future and prevent pruning it for that duration.

**Comment by n8maninger** [comment]
Use block heights

**Comment by ChrisSchinnerl** [comment]
Actually scratch that. We can just keep them forever or until we either delete the object that it is part of or until the host tells us that it can't pin the sector cause it doesn't have it.
