### ISSUE TITLE
Wallet: Create fake transactions for payouts

### ISSUE THREAD

**Issue by n8maninger** [SiaFoundation/renterd#255]
The wallet transaction list does not show sc inflows from returned allowance which is confusing to the user and also means manually computing the balance sparkline is not accurate.

Contract payouts are not technically transactions. hostd handles this by creating fake transactions for the payouts after they mature, could probably do something similar in renterd https://github.com/SiaFoundation/hostd/blob/bdf30348f1cf974bb1e66b2ee9494735399953ef/wallet/wallet.go#L466-L512

**Comment by lukechampine** [comment]
The approach I'm using in `walletd` is "Events" -- each block is converted into a list of events relevant to the wallet, which can include both regular transactions and things like DSCO maturation, storage proofs, file contract revisions, and even host announcements: https://github.com/SiaFoundation/walletd/blob/f66c8564329080d405a51878c83675b8a13301d9/wallet/wallet.go#L178-L266

We could probably port this to work with `ConsensusChange` now, but it might be best to wait until it's time to finish porting `renterd` to `core`.

**Comment by n8maninger** [comment]
That is super slick. It'd be difficult to port the contract events to `ConsensusChange`, but everything else would likely be doable.
