### ISSUE TITLE
Spendings displayed incorrectly

### ISSUE THREAD

**Issue by mike76-dev** [SiaFoundation/renterd#259]
I have two contracts (94b98a7983f6786474af2b306a39c570fd82bdf2db3d220d00910de808c734cf and 3d302f6545ed46078aecf8191d8a936a804a682d7127134a9ef0a5a3a3313a7a), which I used to upload about 700MB of data, so upload spendings are about 7 and 8mS, respectively (as displayed in the UI). I have also downloaded about 10GB, but both download and fund account spendings are still 0H.

**Comment by mike76-dev** [comment]
The 1. is indeed unlikely.
The 2. is more likely, because another contract could be formed with the same host, but in that case the previous contract should be invalidated. I will keep an eye on it, thanks.

**Comment by ChrisSchinnerl** [comment]
You could try to verify that the account is already funded by curling the `/api/bus/accounts` and checking the account for the host in question.

**Comment by mike76-dev** [comment]
Oh I'm sure it is funded, it should happen automatically in the autopilot loop, but the funding doesn't make it to the display.
Btw, I'm struggling with curling the accounts. I think the reason is this:
`"POST   /accounts/:id":              b.accountHandlerGET,`
