### ISSUE TITLE
Bug: upload succeeded but file is not uploaded if directory contains characters like "ś"

### ISSUE THREAD

**Issue by artur9010** [SiaFoundation/renterd#308]
How to reproduce:
- Go to renterd webui
- Create folder with name like testśśśś
- Try to upload a file
- Upload success, but health info is missing
- Try to download file

Can't download or remove file from webui. Not tested via api.
It only applies to files that are in a directory that contains those characters, files with name like "testśśś.iso" works fine.

<img width="1116" alt="Screenshot 2023-04-25 at 13 35 44" src="https://user-images.githubusercontent.com/4835677/234264594-7049220a-0928-49e8-af79-07eaef654188.png">

**Comment by ChrisSchinnerl** [comment]
Thanks for reporting that! I'll take a look right away.

**Comment by ChrisSchinnerl** [comment]
The fix for the backend is merged, the fix for the [UI](https://github.com/SiaFoundation/web/pull/273) too and `master` was updated to use the fixed UI.
