### ISSUE TITLE
Weird behavior after prolonged shutdown

### ISSUE THREAD

**Issue by mike76-dev** [SiaFoundation/renterd#343]
I have been away for 6 days, during which `renterd` has been shut down, and all active contracts have expired.
Upon the start (after updating to the latest `master`), the autopilot loop has archived 24 expired contracts and formed 1 new (it tried to form 2 but one formation failed). The second loop iteration successfully formed 20 new contracts (this is my configured amount), although I believe it should have formed the contracts during the first iteration already.
Still, I have 50 active contracts, of which 29 are far beyond the expiration height, both shown in the UI and when using `curl`:
![image](https://user-images.githubusercontent.com/72828450/236648857-5671f029-45d2-4de4-af8a-a90a047a0c98.png)
Also, both of my two uploaded files show a 100% health while both having 0 shards (obviously, because there are no contracts left):
![image](https://user-images.githubusercontent.com/72828450/236648923-2c67168c-437a-48b4-b681-a66e8ad6101c.png)
The migrator also reports that there are no slabs to migrate (which is obviously wrong).

**Comment by ChrisSchinnerl** [comment]
Could you provide some additional infos such as the output of the active contracts fuel command and the logs? Either here or on discord if you prefer that? 

It would also be useful to know your full autopilot configuration.

**Comment by mike76-dev** [comment]
[contracts.txt](https://github.com/SiaFoundation/renterd/files/11414807/contracts.txt)
[log.txt](https://github.com/SiaFoundation/renterd/files/11414810/log.txt)
[config.txt](https://github.com/SiaFoundation/renterd/files/11414813/config.txt)

**Comment by artur9010** [comment]
<img width="634" alt="Screenshot 2023-05-08 at 07 23 45" src="https://user-images.githubusercontent.com/4835677/236740767-90380bf5-a59d-479d-bc37-abe30f6853a2.png">
same problem here, latest master.

Autopilot config

```json
{
  "Config": {
    "wallet": {
      "defragThreshold": 1000
    },
    "hosts": {
      "allowRedundantIPs": false,
      "maxDowntimeHours": 0,
      "scoreOverrides": null
    },
    "contracts": {
      "set": "autopilot",
      "amount": 50,
      "allowance": "2500000000000000000000000000",
      "period": 6048,
      "renewWindow": 2016,
      "download": 2199023255552,
      "upload": 2199023255552,
      "storage": 2199023255552
    }
  }
}
```

**Comment by mike76-dev** [comment]
Can the file health be 100%, because the files are still available at the original location?

**Comment by peterjan** [comment]
No need to close this out yet. I don't think #347 fixes all of the issues outlined in this issue. I'm looking into the unhealthy slabs query to see whether I can fix the 0/0 100% health thing, that's probably a side-effect of the update to downloads where we download from all contracts in the set, not just the ones in the contract set.

**Comment by ChrisSchinnerl** [comment]
Closing this for now since the issues seem to be resolved.
