### ISSUE TITLE
UI: undefined is not an object (evaluating 'e.storageProofs')

### ISSUE THREAD

**Issue by n8maninger** [SiaFoundation/renterd#378]
When accessing the wallet page, the UI becomes inaccessible and prompts the user to check the browser console. 

![Screenshot 2023-05-25 at 8 34 05 AM](https://github.com/SiaFoundation/renterd/assets/5544150/f5b8a731-94bb-4740-984c-3eb2d55a1235)
![Screenshot 2023-05-25 at 8 33 46 AM](https://github.com/SiaFoundation/renterd/assets/5544150/7c8641cf-37bd-4a96-bdc9-e0923b4c4d46)

**Comment by ChrisSchinnerl** [comment]
@alexfreska that's probably related to the "fake" transactions we are now creating for contract payouts. These transactions won't actually have all the fields set. So we might want to update the UI to check for "undefined" and then handle it accordingly.
