### ISSUE TITLE
Opening large directories in the webui takes a while.

### ISSUE THREAD

**Issue by CtrlAltDefeat94** [SiaFoundation/renterd#411]
## Describe the bug
It takes a really long time to open large directories.
Vup places all files into the same folder (/s5). Currently this directory has roughly 1600 files.
It takes 1900 calls, 50MB and 30 seconds to load this page.

It looks like the health of each file is loaded when the page is loaded, taking 1 call per file.
Perhaps a workaround would be something like an endpoint that returns only unhealthy files, such that all not-returned files can be assumed healthy when loading the page.

**Comment by alexfreska** [comment]
@CtrlAltDefeat94 I was waiting for this issue to come up 😄. The UI currently fetches the full metadata for each object to display slab and shard counts and to calculate the health which requires all the metadata. @peterjan @ChrisSchinnerl perhaps these three attributes are something we could compute and cache in the daemon and return in the list response - I think it would be worthwhile, the health data especially is quite useful.
