### ISSUE TITLE
different behaviour up/downloading via /worker/objects/

### ISSUE THREAD

**Issue by CtrlAltDefeat94** [SiaFoundation/renterd#425]
## Describe the bug
Up and downloadingvia /worker/objects/ using a double slash (eg. /worker/objects//path/to/file.jpeg) results in different behaviour.

I've been testing with different redundancies, and ran into issues when using too many hosts on the testnet, so I decided to reupload the same files, meaning the redundancy would update to the latest settings.
However I made a mistake in my url generation, resulting in a double slash in the path.

When I download the file (GET /worker/objects//path), I can download the file without issue.
When I upload the file (PUT /worker/objects//path), the file is reuploaded to a folder named `/`, rather than the original path.

An additional thing. It's impossible to open this directory in the webui, even when changing the url to visit the directory directly.

**Comment by CtrlAltDefeat94** [comment]
I also noticed that when I request the data of the directory `//` (/worker/objects//), I get returned the data of the directory `/`
So I'm not sure what's in that folder, and what I need to delete to get rid of it.

**Comment by peterjan** [comment]
This sparked some internal discussion that led to some changes being implemented right now. After those changes (https://github.com/SiaFoundation/renterd/pull/460) we can update the UI and prevent the worker from creating objects that end in a `/`.
