### ISSUE TITLE
Endpoint to bulk scan hosts

### ISSUE THREAD

**Issue by pcfreak30** [SiaFoundation/renterd#452]
I would like to see an endpoint like `/api/worker/rhp/scan` that can bulk scan all hosts or just ones deemed unusable as a manual trigger. 

Ive had to write a bash script to parse out the hosts endpoint and manually trigger host scans to do this.

**Comment by ChrisSchinnerl** [comment]
Closing this since writing a for-loop doesn't seem to be a sufficient hinderance to add a full endpoint.
