### ISSUE TITLE
UX: Dashboard Statistics 

### ISSUE THREAD

**Issue by pcfreak30** [SiaFoundation/renterd#453]
Would like to see stats that show the average upload, download, storage, and contract prices from active contracts/hosts. It should also show the number of active contracts, in real time, ideally as a simple number, as well as number of active and usable hosts.

Should also be able to select based on date/time ranges.

Overall should be a simple analytics dashboard, probably as a dedicated page in the left-hand menu.

**Comment by ChrisSchinnerl** [comment]
Superseded by https://github.com/SiaFoundation/renterd/issues/695
