### ISSUE TITLE
UI: Contract Set Contracts Filter

### ISSUE THREAD

**Issue by pcfreak30** [SiaFoundation/renterd#454]
The contracts page should have a filter, or just by default show only the contracts that are truly active, which IIRC is the equiv to `/api/bus/contracts/set/autopilot`

**Comment by peterjan** [comment]
I think the contracts page should indeed have an option to filter on contract set contracts, or have some indication on what contracts belong the configured contract set. I took the liberty of updating the issue title a bit to reflect this.

**Comment by peterjan** [comment]
duplicate of https://github.com/SiaFoundation/renterd/issues/716
