### ISSUE TITLE
File health view

### ISSUE THREAD

**Issue by multikatt** [SiaFoundation/renterd#492]
## Describe the bug
I have a couple of slabs that has been failing to migrate for a few days now, due to excessive fiddling on my part. I've decided to reupload those files now, since the hosts that has the slabs doesn't seem to be coming online again. At this point that requires me to hunt in the db for the slab, then the slice with that slab to find the object id, then the filename in `objects`. It would be nice to view which files has been failing to migrate, maybe with an alert, for x hours. Also, when looking up the files in the ui now it says they have "excellent health" with a green check mark, which isn't true.

**Comment by alexfreska** [comment]
Hey thank you for the bug report. We are in the process of merging a few related changes. 

The UI will include a new alerts feature in the next release, @chris124567 @peterjan does the alerts feature in include anything for failing migrations?

Also there was an issue with the health breakdown, we have updated it to be accurate and also explain health with more detail.

**Comment by ChrisSchinnerl** [comment]
Not yet but it's on the roadmap

**Comment by ChrisSchinnerl** [comment]
https://github.com/SiaFoundation/renterd/pull/545 will make this a bit easier. When a slab fails to migrate an alert will be registered that contains the slab's key which can be used with the new endpoint to fetch the list of objects the slab is part of.

The UI will be updated to make use of the new endpoint soon.

**Comment by ChrisSchinnerl** [comment]
https://github.com/SiaFoundation/renterd/pull/545 will make this a bit easier. When a slab fails to migrate an alert will be registered that contains the slab's key which can be used with the new endpoint to fetch the list of objects the slab is part of.

The UI will be updated to make use of the new endpoint soon.

**Comment by alexfreska** [comment]
Fixed https://github.com/SiaFoundation/renterd/pull/534
