### ISSUE TITLE
WebUI page "Hosts" reporting "no hosts in the database" until renterd is fully configured

### ISSUE THREAD

**Issue by jesta030** [SiaFoundation/renterd#500]
## Describe the bug
When spinning up a fresh instance of renterd the following behaviour was observed:

1. Hosts will not be scanned even with a fully synced node until "Autopilot" is configured
- Running `$curl --user :$Pass --location '$IP:$PORT/api/bus/hosts'` returns all announced hosts but all are `"scanned": false`
- The WebUI shows "There are currently no hosts in the database. Make sure renterd can access the network and make sure peers are being discovered."

2. Configuring "Autopilot" results in the hosts being scanned
- Logs show messages like `scanning 1000 hosts in range 2000-3000`
- Running `$curl --user :$Pass --location '$IP:$PORT/api/bus/hosts'` returns all announced hosts and all are `"scanned": true` and their price tables are populated now
- The webUI still shows the same message as above

3. Filling out all options on the page "Configuration" finally populates the page "Hosts" with the scanned hosts and their settings.

## Expected behaviour
Since upon syncing the blockchain all hosts and their current address are known, they should immediately be scanned for their settings/prices and then be displayed on the "Hosts" page even if no autopilot/gouging is set. Fields that need these settings should display a question mark and a message to tell the user to configure autopilot/gouging to calculate them.
This would improve UX since it makes the software more accessible to users by showing available hosts without the need to dive deeper into the meaning of available parameters. This would also allow renterd to be used for cases where the built-in tools of renterd are to be used for other purposes than only renting like quickly checking hosts or calculating network metrics.

### General Information/Config
UnRAID, Docker, ghcr.io/siafoundation/renterd:master

**Autopilot Config**

```
{
        "contracts": {
                "set": "autopilot",
                "amount": 0,
                "allowance": "0",
                "period": 12096,
                "renewWindow": 3024,
                "download": 0,
                "upload": 0,
                "storage": 0
        },
        "hosts": {
                "allowRedundantIPs": false,
                "maxDowntimeHours": 720,
                "scoreOverrides": null
        },
        "wallet": {
                "defragThreshold": 1000
        }
}
```

**Bus Config**

```
{
        "minShards": 10,
        "totalShards": 30
}

{
        "hostBlockHeightLeeway": 6,
        "maxContractPrice": "15000000000000000000000000",
        "maxDownloadPrice": "3000000000000000000000000000",
        "maxRPCPrice": "1000000000000000000000",
        "maxStoragePrice": "631593542897",
        "maxUploadPrice": "3000000000000000000000000000",
        "minAccountExpiry": 86400000000000,
        "minMaxCollateral": "10000000000000000000000000",
        "minMaxEphemeralAccountBalance": "1000000000000000000000000",
        "minPriceTableValidity": 300000000000
}
(Unmodified)
```

**Contract Set Contracts**

```
none
```

**Comment by ChrisSchinnerl** [comment]
@alexfreska How do you feel about this solution? https://github.com/SiaFoundation/renterd/pull/523

**Comment by alexfreska** [comment]
@ChrisSchinnerl would this return before autopilot is configured? or would this only fix the step #3 issue of hosts sometimes not returning right away after everything is configured?

**Comment by ChrisSchinnerl** [comment]
> @ChrisSchinnerl would this return before autopilot is configured? or would this only fix the step 3 issue of hosts sometimes not returning right away after everything is configured?

This should cause hosts to always be returned for the 'all' filter regardless of the state of configuration.

**Comment by alexfreska** [comment]
@ChrisSchinnerl amazing, ship it
