### ISSUE TITLE
Error when saving the autopilot config

### ISSUE THREAD

**Issue by mike76-dev** [SiaFoundation/renterd#503]
## Describe the bug
When configuring the autopilot on a fresh `renter` node and saving the changes, an `undefined is not an object (evaluating 'i.default')` error pops up.

## Expected behaviour
No error messages should appear.

## Additional context
The config is saved successfully, though.

### General Information
Are you running a fork of `renterd`? Yes, but this part of code is untouched.
Are you on the mainnet or on the testnet? Mainnet.

### Renterd Config
Please provide us the following information:

**Autopilot Config**

```bash
curl -u ":[YOUR_PASSWORD]" http://localhost:9980/api/autopilot/config
```

**Bus Config**

```bash
curl -u ":[YOUR_PASSWORD]" http://localhost:9980/api/bus/setting/redundancy

curl -u ":[YOUR_PASSWORD]" http://localhost:9980/api/bus/setting/gouging
{
	"minShards": 3,
	"totalShards": 9
}
{
	"hostBlockHeightLeeway": 6,
	"maxContractPrice": "15000000000000000000000000",
	"maxDownloadPrice": "3000000000000000000000000000",
	"maxRPCPrice": "1000000000000000000000",
	"maxStoragePrice": "631593542901",
	"maxUploadPrice": "3000000000000000000000000000",
	"minAccountExpiry": 86400000000000,
	"minMaxCollateral": "10000000000000000000000000",
	"minMaxEphemeralAccountBalance": "1000000000000000000000000",
	"minPriceTableValidity": 300000000000
}```

**Contract Set Contracts**

```bash
curl -u ":[YOUR_PASSWORD]" http://localhost:9980/api/bus/contracts/set/autopilot | grep '"id"' | wc -l
[]
```

### Renterd Logs
If applicable, upload your `renterd.log` file or part of the file you think is relevant to the issue.

**Comment by new0nebit** [comment]
Wow, I just came here to report this error, but then I saw that you had already done it 😅👍

But also I noticed a curious detail, if you enter all the values in the `'Configuration'` tab **BEFORE** configuring the `'Autopilot'` tab this error does not show up. Idk, maybe this small detail help devs to find a bug 🤷‍♂️

**Comment by alexfreska** [comment]
Hey thank you both for reporting this. The sync default contract set feature was causing the issue when the default contract set was not yet set. I've put together a fix that will go into the next release.
<img width="489" alt="Screenshot 2023-08-02 at 2 48 17 PM" src="https://github.com/SiaFoundation/renterd/assets/1412796/641e803a-8e45-456e-9c95-7c0f29f25e47">

**Comment by peterjan** [comment]
we merged UI recently so this should be fixed, closing this out but feel free to re-open should there be any issues
