### ISSUE TITLE
Feature/Idea: E-Mail alerts on low wallet balance

### ISSUE THREAD

**Issue by pcfreak30** [SiaFoundation/renterd#520]
This is something that I think is very useful, though it could be a grant project, it would make more sense as part of the core server.

If the wallet balance is dangerously close to putting the data at risk, an email should be able to be sent. This could probably be extended to a generalized webhook API even, but I think email is a **good enough** starting point.

If it is deemed better for this to be outside the core software I would request that an outline by the core team be given on how this could be achieved with the rest API to gather the needed info, so that it could be more easily tackled by a grant.

Kudos!

**Comment by mike76-dev** [comment]
Regardless of _how exactly_ it should be implemented, this feature could be useful for the hosts, too, because an empty wallet puts the contracts at risk as well.

**Comment by NickJH** [comment]
If the apps are packaged for Linux this becomes relatively trivial. If it is a deb package, the package would need a Requires of mailutils. EL7 requires mailx. Then it is just a question of a mini cron script.

If the apps are not going to be packaged and remain self-contained then a go mailer would be needed.

You can end up with other issues and this is only a particularly good idea for self-hosted solutions or for people with a valid mail-serving set up. As an example, if you try send an alert to a Gmail address, it will be spammed unless you have an spf record for the sending domain. If you are sending to s GMX address, it will be totally rejected if you don't have a valid, non-generic PTR record for your external IP address.

**Comment by pcfreak30** [comment]
My view is more of using SMTP access to a mail server account, not using a local MTA. Mail servers are a PITA to manage and I outsource mine.

**Comment by pcfreak30** [comment]
https://github.com/orgs/SiaFoundation/projects/5?pane=issue&itemId=29928075 seems relevant.

**Comment by peterjan** [comment]
I'll add a low balance alert so in the event the wallet is low on funds an alert will be returned by the alerter module (exposed through the autopilot's API). I think for the time being we will leave it at that, anyone that wants to tie it into a mailing service can periodically query our API and take action when new alerts appear.

**Comment by pcfreak30** [comment]
One thing that could be related and useful on this, maybe in the future is a webhook system for the alerts so you dont need to poll?

**Comment by peterjan** [comment]
I'll close out this issue though after merging the new alert. Feel free to open a dedicated issue although its' not necessary to fill the backlog with these types of enhancements or nice-to-haves. There's plenty of stuff we are thinking of adding in the future but for the time being we're still building out core functionality and will focus on stability before introducing bells and whistles like a webhooks API. 

Webhooks API would be cool though 😆
