### ISSUE TITLE
UI: Update tooltip to include version information

### ISSUE THREAD

**Issue by new0nebit** [SiaFoundation/renterd#521]
## Describe the bug
In `renterd` I badly miss a tooltip about what version of `renterd` I have running, similar to the message hint as in `hostd`.

## Expected behaviour

<img width="305" alt="version" src="https://github.com/SiaFoundation/renterd/assets/17514297/59c0e624-9b72-4cb6-a081-173163eaec48">

**Comment by alexfreska** [comment]
Agreed, would be great to match hostd. @peterjan the information is powered by this hostd endpoint: https://api.sia.tech/hostd#32ef7651-c2c1-43c6-89d3-f17c188b4667 we could do a similar one on renterd minus public key.

**Comment by peterjan** [comment]
this just got merged into `master` so it can be incorporated in the UI

**Comment by new0nebit** [comment]
Now tooltip is completely broken in Zen testnet. The tooltip informs that renterd is running in mainnet, but `renterd` is running in Zen. I also don't see the `renterd` version. Sorry, I don't get it, has it been added or is it still in the plans and under development?

<img width="321" alt="Screenshot 2023-08-18 в 21 38 32" src="https://github.com/SiaFoundation/renterd/assets/17514297/f9486e6e-6c18-46d3-84af-a5fb81a3b0be">

**Comment by alexfreska** [comment]
@new0nebit hey there sorry about that, the `master` branch can be unstable sometimes do to the need for UI dependencies to be merged. I am not sure why it says mainnet there, but regardless, I have UI changes that totally update the way the network is displayed and also add the version info. We can keep this open until the UI changes make it into `renterd`. Thank you for your patience! 🙏🏼  https://github.com/SiaFoundation/web/pull/353

**Comment by new0nebit** [comment]
@alexfreska Great! However, the tooltip still incorrectly indicates which environment `renterd` is running in. In my case, `renterd` is running in Zen, but the tooltip still states that `renterd` is launched in the Mainnet. I also noticed that the large orange banner in the header with the message "_You are on the Zen Testnet_." has disappeared.

<img width="318" alt="Screenshot" src="https://github.com/SiaFoundation/renterd/assets/17514297/79be2751-32ab-4bf9-a1f4-269a0439ffa8">

**Comment by alexfreska** [comment]
@new0nebit arg, very odd. @peterjan the UI expects these values https://github.com/SiaFoundation/renterd/blob/c562e69248be479fe5638937fa8e1f7b838115cd/build/network.go#L16 I just did a testnet build locally and it does seem to return "Mainnet", is it possible there is an issue on the daemon side?

**Comment by alexfreska** [comment]
@new0nebit this should now be fixed: https://github.com/SiaFoundation/renterd/pull/568

**Comment by new0nebit** [comment]
@alexfreska Fixed! Closed 🙏
