### ISSUE TITLE
"Application error: a client-side exception has occurred" when clicking alerts

### ISSUE THREAD

**Issue by multikatt** [SiaFoundation/renterd#557]
## Describe the bug
Using cf082d665d502e127ed2571fc4f56d00cd853264 I'm getting
`Application error: a client-side exception has occurred (see the browser console for more information).`
on a full black text on white background page as soon as i click the alert button. According to the icon in the left hand i apparently have 32 active alerts at the moment:
![image](https://github.com/SiaFoundation/renterd/assets/389800/22458ab2-64a8-4ba7-b510-5678a0f2f68e)

Checking out the console im seeing a few similar errors:
```
Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7Bfcid%3Ae7ec85c5931ffdec5bbc2d8064bbff20627e4eb3e73d70e9a19615eb7b5d5ffc%7D for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    NextJS 63
framework-5bb4f355ac165f9a.js:9:69816
    NextJS 62
```

```
Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7Bfcid%3A1465e45acac337986d6b3a8991d4237502fd5015b950cd6b3cca990469d92ec1%2C%20fcid%3A1d1a0447cf209d51961ba886f6d3589e21bd33b1be0031f420cd6d75fa4bef42%2C%20fcid%3A7e251b414eb5e85ae47d91a9b7ecbc6da14062045e3ecae9f9a4f6a2a65a5a00%2C%20fcid%3A9cbe91f67f3443ad09a686990ec41d9b5eee739637c3452fa2cf0e55076f87ae%2C%20fcid%3Ae5b4a7c29880d56809ba49b34a60d361a6a45833eb256bd50eab16239e398664%7D for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    NextJS 63
framework-5bb4f355ac165f9a.js:9:69816
 ```

```
Error rendering page:  Error: Cancel rendering route
    NextJS 35
main-681772d9d0c9cb0e.js:1:9259
```

Following https://legacy.reactjs.org/docs/error-decoder.html/?args%5B%5D=object%20with%20keys%20%7Bfcid%3A1465e45acac337986d6b3a8991d4237502fd5015b950cd6b3cca990469d92ec1%2C%20fcid%3A1d1a0447cf209d51961ba886f6d3589e21bd33b1be0031f420cd6d75fa4bef42%2C%20fcid%3A7e251b414eb5e85ae47d91a9b7ecbc6da14062045e3ecae9f9a4f6a2a65a5a00%2C%20fcid%3A9cbe91f67f3443ad09a686990ec41d9b5eee739637c3452fa2cf0e55076f87ae%2C%20fcid%3Ae5b4a7c29880d56809ba49b34a60d361a6a45833eb256bd50eab16239e398664%7D&invariant=31 for example returns this full error:
```
Objects are not valid as a React child (found: object with keys {fcid:1465e45acac337986d6b3a8991d4237502fd5015b950cd6b3cca990469d92ec1, fcid:1d1a0447cf209d51961ba886f6d3589e21bd33b1be0031f420cd6d75fa4bef42, fcid:7e251b414eb5e85ae47d91a9b7ecbc6da14062045e3ecae9f9a4f6a2a65a5a00, fcid:9cbe91f67f3443ad09a686990ec41d9b5eee739637c3452fa2cf0e55076f87ae, fcid:e5b4a7c29880d56809ba49b34a60d361a6a45833eb256bd50eab16239e398664}). If you meant to render a collection of children, use an array instead.
```
I've posted the response from /api/bus/alerts here: https://gist.github.com/multikatt/88cfc79a735eb50c793245d9ce9e3302

## Expected behaviour
no error

### General Information
Are you running a fork of `renterd`?
no
Are you on the mainnet or on the testnet?
mainnet

### Renterd Config
Please provide us the following information:

**Autopilot Config**
{
        "contracts": {
                "set": "autopilot",
                "amount": 50,
                "allowance": "12000000000000000000000000000",
                "period": 6048,
                "renewWindow": 2016,
                "download": 3000000000000,
                "upload": 4000000000000,
                "storage": 20000000000000
        },
        "hosts": {
                "allowRedundantIPs": false,
                "maxDowntimeHours": 336,
                "scoreOverrides": null
        },
        "wallet": {
                "defragThreshold": 1000
        }
}
**Bus Config**
{
        "minShards": 10,
        "totalShards": 30
}
{
        "hostBlockHeightLeeway": 6,
        "maxContractPrice": "450000000000000000000000",
        "maxDownloadPrice": "2300000000000000000000000000",
        "maxRPCPrice": "2000000000000000000000",
        "maxStoragePrice": "254629629630",
        "maxUploadPrice": "900000000000000000000000000",
        "minAccountExpiry": 86400000000000,
        "minMaxCollateral": "10000000000000000000000000",
        "minMaxEphemeralAccountBalance": "1000000000000000000000000",
        "minPriceTableValidity": 300000000000
}
**Contract Set Contracts**
50

**Comment by alexfreska** [comment]
Fixed https://github.com/SiaFoundation/renterd/pull/563
