### ISSUE TITLE
Uploads don't disappear from "ongoing uploads" in UI when uploading a large batch of small files

### ISSUE THREAD

**Issue by ChrisSchinnerl** [SiaFoundation/renterd#576]
When uploading a large number of tiny files I noticed that the small window showing the ongoing uploads never goes down to 0 uploads. Often times there are a few uploads left which stick around forever.
After refreshing the screen which should cause any ongoing upload to fail, the object shows up in the UI just fine and I can even download it.

Doing some debugging didn't reveal any stuck code on the backend or errors in the `renterd` logs which leads me to believe that the UI is maybe failing to remove ongoing uploads in some edge cases.

**Comment by alexfreska** [comment]
@ChrisSchinnerl is this the state where it says "processing"? I also noticed that, the upload gets to 100% quickly but then stays processing for either a long while or forever. Let me take a look and see if I can find anything on my end.

**Comment by ChrisSchinnerl** [comment]
Yep it says "processing". Once an upload lingers like that it never disappears unless I refresh the screen. But after refreshing downloading it works just fine.
