### ISSUE TITLE
Cannot dismiss an alert if it overflows

### ISSUE THREAD

**Issue by mike76-dev** [SiaFoundation/renterd#612]
## Describe the bug
If the alert message is too long, the dismiss button is not displayed, so it's not possible to dismiss that particular alert.

## Expected behaviour
The dismiss button should be visible.

## Additional context
![image](https://github.com/SiaFoundation/renterd/assets/72828450/3373392c-a3bd-4f74-8884-8eaa4a9ed810)

### General Information
Are you running a fork of `renterd`?
Are you on the mainnet or on the testnet?

### Renterd Config
Please provide us the following information:

**Autopilot Config**

```bash
curl -u ":[YOUR_PASSWORD]" http://localhost:9980/api/autopilot/config
```

**Bus Config**

```bash
curl -u ":[YOUR_PASSWORD]" http://localhost:9980/api/bus/setting/redundancy

curl -u ":[YOUR_PASSWORD]" http://localhost:9980/api/bus/setting/gouging
```

**Contract Set Contracts**

```bash
curl -u ":[YOUR_PASSWORD]" http://localhost:9980/api/bus/contracts/set/autopilot | grep '"id"' | wc -l
```

### Renterd Logs
If applicable, upload your `renterd.log` file or part of the file you think is relevant to the issue.

**Comment by alexfreska** [comment]
Fixed
