### ISSUE TITLE
Update README.md

### ISSUE THREAD

**Issue by peterjan** [SiaFoundation/renterd#647]
We have been updating our API documentation, but it has been a while since we updated the README. I think at this point it's probably best to rewrite it completely and maybe link to the API documentation where it's appropriate, API docs can be found [here](https://api.sia.tech/renterd).

**Comment by ShatilKhan** [comment]
Hi, please assign me this issue

**Comment by Prtm2110** [comment]
@peterjan please assign this issue to me

**Comment by ChrisSchinnerl** [comment]
Assigning @Prtm2110 since I already assigned 1-2 other issues to @ShatilKhan

**Comment by Prtm2110** [comment]
any specific changes that are to be made?
