### ISSUE TITLE
Deprecate CLI Flags

### ISSUE THREAD

**Issue by peterjan** [SiaFoundation/renterd#648]
The following CLI flags are marked as `DEPRECATED`:
- `db.password`
- `bus.apiPassword`
- `bus.remoteAddr`
- `worker.apiPassword`
- `worker.remoteAddrs`

They should be removed and everyone should use their env variable counterparts, or through yaml.

**Comment by ShatilKhan** [comment]
Hi, please assign me this issue

**Comment by dbarnwal** [comment]
can i take this one ?

**Comment by ShatilKhan** [comment]
Hi @peterjan 
Can you tell me which files need to be updated?

**Comment by ChrisSchinnerl** [comment]
@ShatilKhan you can find the CLI flags in `cmd/renterd/main.go`
