### ISSUE TITLE
Make CLI Setup More Verbose and User-Friendly

### ISSUE THREAD

**Issue by n8maninger** [SiaFoundation/renterd#672]
Introduce more verbose messages and interactive prompts to guide the user through the setup process. The goal is to make the CLI more user-friendly and informative.

### If the user has not set an API password via yml or environment variable they are prompted with the text
```
Please choose a password to unlock the UI
(The password must be at least 4 characters)
Enter password: 
```

### If the user has not set a wallet seed via yml or environment variable they are prompted with the text
```
Type in your 12-word seed phrase and press enter. If you do not have a seed phrase yet, type 'seed' to generate one
Enter seed phrase:
```

### If the user generates a new seed phrase
```
A new seed phrase has been generated below. Write it down and keep it safe.
Your seed phrase is the only way to recover your Siacoin. If you lose your seed phrase, you will also lose your Siacoin.
You will need to re-enter this seed phrase every time you start renterd.

Seed Phrase: key favorite potato flock zebra unhappy design buffalo shed pole festival spice
Wallet Address: 680d67e2521b7f7645134fd0ac0b3c0c72a99f16f4bed1bc9ff1af6e8a936a2133883fce3e19

Please type your seed phrase to confirm and press enter to continue
Enter seed phrase:
```

### If the typed seed phrase does not match
```
Seed phrases do not match!
You entered: key favorite potato flock zebra unhappy design buffalo shed pole spice festival
Actual phrase: key favorite potato flock zebra unhappy design buffalo shed pole festival spice

Please type your seed phrase to confirm and press enter to continue
Enter seed phrase:
```

**Comment by sagar2395** [comment]
@n8maninger I would like to work on this

**Comment by n8maninger** [comment]
> @n8maninger I would like to work on this

Awesome! We’ve got a similar flow in hostd if you’re looking for an example https://github.com/SiaFoundation/hostd/blob/920057ff41c889c08d319577802de6c02e77a57e/cmd/hostd/main.go#L69

There is some logic unique to renterd that will need to be maintained though. Ping me, Chris or PJ if you get stuck

**Comment by sagar2395** [comment]
@n8maninger @peterjan Hi, I have updated cli comments as requested, Only thing remaining is I am unable to print wallet address in CLI. Could you please help for this ?
 I tried using the approach used in hostd, but there is version mismatch in core/types which is causing issues.
I also tried updating the version, but it is causing issue in other files.

**Comment by n8maninger** [comment]
> @n8maninger @peterjan Hi, I have updated cli comments as requested, Only thing remaining is I am unable to print wallet address in CLI. Could you please help for this ? I tried using the approach used in hostd, but there is version mismatch in core/types which is causing issues. I also tried updating the version, but it is causing issue in other files.

This should work:
```go
if err := wallet.SeedFromPhrase(&seed, phrase); err != nil {
    panic(err)
}
key := wallet.KeyFromSeed(&seed, 0)
address := key.PublicKey().StandardAddress()
```

**Comment by sagar2395** [comment]
@n8maninger Thanks for the help. It's done. Please check.

**Comment by ChrisSchinnerl** [comment]
Unassigning since this has been stale for a while

**Comment by n8maninger** [comment]
We improved this with `renterd config`. I'm okay with closing this entirely.
