### ISSUE TITLE
Incorrect/incomplete explanation of the upload packing

### ISSUE THREAD

**Issue by mike76-dev** [SiaFoundation/renterd#681]
## Describe the bug
```Data on the Sia network is stored in 40MiB sectors so by default uploaded files are divided and padded into these 40MiB peices. This means that storage is wasted on padding but more importantly files smaller than 40MiB still use 40MiB of space. Upload packing avoids this waste by buffering files and packing them together before they are uploaded to the network. This trades some performance for storage efficiency. It is also important to note that because buffered files are temporarily stored on disk they must be considered when backing up your renterd data.```

## Expected behaviour
If I understand correctly, the data is stored in 4MiB sectors, so the uploaded files take minimum 40MiB of space only with the default redundancy settings (10/30). If a custom redundancy is set, the space occupied is different.

## Additional context
![image](https://github.com/SiaFoundation/renterd/assets/72828450/a5a76ea6-e3d5-4176-a995-bd138edcf7fd)

### General Information
Are you running a fork of `renterd`? N/A
Are you on the mainnet or on the testnet? N/A

**Comment by ChrisSchinnerl** [comment]
That's correct. Data is stored in 4 MiB sectors on host. When you upload using the default redundancy (10 out of 30 pieces where each piece is 1 sector) you end up splitting a file into 40MiB chunks which are encoded into 120MiB slabs.
So uploading 1 MiB would result in that 1 MiB to be padded to 40 MiB, then encoded to 120 MiB and as a result cause the user to pay for 120 MiB of storage on hosts.

**Comment by mike76-dev** [comment]
Perfect!
