### ISSUE TITLE
Deleting all files from a bucket in the UI

### ISSUE THREAD

**Issue by mike76-dev** [SiaFoundation/renterd#685]
## Describe the bug
I have two buckets (1). If I delete all files from a bucket (2), suddenly all my buckets are gone and I end up with the upload drag&drop box (3). Wait, if I click on the Files icon, all my buckets are there again, tada (4)! But it's very confusing.

## Expected behaviour
After deleting all files from a bucket, the bucket view should be displayed right away.

## Additional context
(1) ![image](https://github.com/SiaFoundation/renterd/assets/72828450/9066237e-16d8-4f6c-87a2-1be2b78d7270)
(2) ![image](https://github.com/SiaFoundation/renterd/assets/72828450/c8fd3c11-fc8e-4f08-91ab-a269d473cf67)
(3) ![image](https://github.com/SiaFoundation/renterd/assets/72828450/0953c1ba-85c7-42fa-8c63-91f818bd824d)
(4) ![image](https://github.com/SiaFoundation/renterd/assets/72828450/9ef6d5e4-ca6f-4708-8f45-3cb0761fb961)

### General Information
Are you running a fork of `renterd`? N/A
Are you on the mainnet or on the testnet? N/A

**Comment by alexfreska** [comment]
@mike76-dev hey I'm not sure I can recreate this issue, are these the correct steps: https://ipfs.rift.sh/ipfs/QmR4KdwSEPXrEvGQgg5uPfP1t9LgiG6dTzX5yHe7oAfEvU

**Comment by mike76-dev** [comment]
This is what I did:
1. Upload one file to the `default` bucket.
2. Create another bucket named `new`.
3. Upload one (actually, the same) file to the `new` bucket.
4. Delete the file from the `new` bucket.

**Comment by alexfreska** [comment]
> I have two buckets (1). If I delete all files from a bucket (2), suddenly all my buckets are gone and I end up with the upload drag&drop box

Here you still viewing the bucket but there are 0 files, so it shows the drag & drop box.

> (3). Wait, if I click on the Files icon, all my buckets are there again, tada (4)! But it's very confusing.

Here you are navigating back to the bucket list which shows you the buckets.

Ah I see, I guess its a UX question, why do you expect to see the bucket list after deleting the last file in the bucket? Isn't it logical to see the empty bucket, and then if you can choose to upload a new file or to navigate to the bucket list?

**Comment by mike76-dev** [comment]
I get your point now.
Indeed, after deleting all files I should expect to be in the same (empty) bucket, but I’m also expecting to see a `..` button to navigate a level up, like there is in a non-empty bucket, but that is hidden by the drag&drop box.
This is a tricky challenge, not sure how to handle it.

**Comment by alexfreska** [comment]
@mike76-dev ah I can see the lack of navigation being confusing, as clicking "Files" is not as obvious, I can add a .. or a very clear back to buckets button in the drag and drop state.

**Comment by mike76-dev** [comment]
I think that should do it, indeed!

**Comment by peterjan** [comment]
this is fixed, button was added
