### ISSUE TITLE
Cant create docker img

### ISSUE THREAD

**Issue by hackschnitzel09** [SiaFoundation/renterd#701]
Hi, i geht an error when creating the docker img.
Error: `ERROR: failed to solve: process "/bin/sh -c if [ \"$BUILD_RUN_GO_GENERATE\" = \"true\" ] ; then go generate ./... ; fi" did not complete successfully: exit code: 1`

**Comment by ChrisSchinnerl** [comment]
@hackschnitzel09 can you try fetching the code via `git`? Seems like the error `fatal: not a git repository (or any of the parent directories): .git` might be related to the missing git-related files. 
Either that or run it with `BUILD_RUN_GO_GENERATE` set to `false` to avoid the `go generate` step.
