### ISSUE TITLE
Autopilot/Config pricing should be reviewed

### ISSUE THREAD

**Issue by pcfreak30** [SiaFoundation/renterd#709]
It is unclear on how the average pricing is computed in the autopilot. If it uses siacentral, then it should be decided if it will stay that way vs using siascan which is evolving. If it is fully self-hosted, the algorithm should probably be documented, and optionally enable deferring to siascan.

What is clear is the current pricing does not reflect siascan.

But the source of the data should also be documented, and possibly a tooltip added for the end user.

**Comment by peterjan** [comment]
closing this out in favour of https://github.com/SiaFoundation/renterd/issues/710  - it's not exactly a duplicate but too similar to have two issues for
