### ISSUE TITLE
Add contracts column that shows whether contract is part of default set

### ISSUE THREAD

**Issue by ChrisSchinnerl** [SiaFoundation/renterd#716]

**Comment by alexfreska** [comment]
@ChrisSchinnerl could we add a `sets` key to the contracts list response, eg: `sets: ['autopilot', 'other']`, that would simplify this feature and also allow me to display and filter on all of a contracts sets.

**Comment by alexfreska** [comment]
Added https://github.com/SiaFoundation/web/releases/tag/renterd%400.39.0

<img width="762" alt="Screenshot 2024-02-05 at 9 15 03 AM" src="https://github.com/SiaFoundation/renterd/assets/1412796/9051a882-634a-432e-a4bc-60f553db0602">
