### ISSUE TITLE
Optimise pruneSlabs

### ISSUE THREAD

**Issue by ChrisSchinnerl** [SiaFoundation/renterd#719]
`pruneSlabs` currently gets called every time we call `UpdateObject`.
It's a very expensive call that might take multiple seconds on large databases so we should not call it too frequently.

I'd suggest either
1. implementing more specialised versions of it which don't scan all slabs but only the ones that belong to a specific object or multipart upload etc. Then we call these specialised versions instead. The current `pruneSlabs` function can still be called on startup before cleaning up unused buffers.
2. not cleaning up slabs immediately and instead only periodically calling `pruneSlabs`.

The downside of 2 is that the stats won't update immediately for a user in the UI and also that we still perform the expensive operation on a running system. 1. would only try to touch slabs that might have become obsolete and only perform a full cleanup on startup for extra safety.

**Comment by peterjan** [comment]
was looking into this and found it's not that slow on `areq`

```
{"level":"warn","date":"2023-10-31T10:43:15Z","component":"db","msg":"SLOW SQL >= 100ms","elapsed":"2021.532ms","rows":6,"sql":"DELETE FROM slabs WHERE slabs.id
{"level":"warn","date":"2023-10-31T10:43:32Z","component":"db","msg":"SLOW SQL >= 100ms","elapsed":"1188.295ms","rows":0,"sql":"DELETE FROM slabs WHERE slabs.id
```

```sql

EXPLAIN QUERY PLAN 
SELECT sla.id FROM slabs sla
LEFT JOIN slices sli ON sli.db_slab_id  = sla.id
WHERE db_object_id IS NULL AND db_multipart_part_id IS NULL AND sla.db_buffered_slab_id IS NULL

-- SEARCH TABLE slabs AS sla USING COVERING INDEX idx_slabs_db_buffered_slab_id (db_buffered_slab_id=?)
-- SEARCH TABLE slices AS sli USING INDEX idx_slices_db_slab_id (db_slab_id=?)

```

Could be hdd vs ssd indeed as you suggested. The reason I wanted to bring this up is that if the problem is not critical (as areq logs suggest), I would probably lean towards a #2 type solution. What if we do a variation of #2 that makes sure we only run it onc every 15' and potentially limit the number of slabs we prune.

**Comment by ChrisSchinnerl** [comment]
It's not node-killing slow but saving 1-2s of locking by not trying to prune all slabs from the whole db every time we delete an object would be a big win.
On my node the problem was trying to reupload thousands of files taking forever because it would block for seconds on every upload.
So at the very least I'd change `deleteObject` which we call in `UpdateObject` to only prune slabs related to the object we just deleted.
