### ISSUE TITLE
UI doesn't report upload error, file disappears from UI

### ISSUE THREAD

**Issue by timrettop** [SiaFoundation/renterd#725]
## Describe the bug
I got to the state of having enough contracts to upload files.  After a couple other test uploads, I attempted a 200MB file which showed as uploading, then later didn't show any details.  I later find in the logs this error: 
```2023-11-08T13:47:14Z    ERROR   uploadmanager   worker/upload.go:1113   failed to relaunch a sector upload, err no candidate uploader found```
The UI doesn't show the file, or any errors. 

## Expected behaviour
The UI should indicate that there was an error, ideally re-attempting the request or prompting the user

### General Information

mainnet - container from master, version 0e687ab

### Renterd Config
Please provide us the following information:

**Autopilot Config**

```{
	"contracts": {
		"set": "autopilot",
		"amount": 50,
		"allowance": "1120000000000000000000000000",
		"period": 6048,
		"renewWindow": 2016,
		"download": 140000000000,
		"upload": 140000000000,
		"storage": 1000000000000
	},
	"hosts": {
		"allowRedundantIPs": false,
		"maxDowntimeHours": 1440,
		"scoreOverrides": null
	},
	"wallet": {
		"defragThreshold": 1000
	}
}
```

**Bus Config**

```bash
{
	"minShards": 10,
	"totalShards": 30
}

{
	"hostBlockHeightLeeway": 6,
	"maxContractPrice": "166000000000000000000000",
	"maxDownloadPrice": "521000000000000000000000000",
	"maxRPCPrice": "1000000000000000000000",
	"maxStoragePrice": "53626543210",
	"maxUploadPrice": "53666666666666666666666667",
	"minAccountExpiry": 86400000000000,
	"minMaxCollateral": "10000000000000000000000000",
	"minMaxEphemeralAccountBalance": "1000000000000000000000000",
	"minPriceTableValidity": 300000000000
}```

**Contract Set Contracts**

```33```

### Renterd Logs

There is no other uploadmanager logs or anything relevant around the error log.

**Comment by peterjan** [comment]
I'm closing this out, this has been fixed, we register an alert now on both upload and download errors. We've also identified some issues in the upload code and have fixed them so these errors shouldn't be happening anymore in the first place.
