### ISSUE TITLE
Consider lost sectors when scoring hosts

### ISSUE THREAD

**Issue by ChrisSchinnerl** [SiaFoundation/renterd#731]
In `DeleteHostSector` we should increment a counter on the host whenever a sector is deleted from a host IFF the sector had a link to a contract with said host.

We also introduce a max number of data a host can lose which has a sane default and can be configured by the user.

Finally we update the scoring algorithm to apply a score multiplier to the host's score in the range 0-1.
0 when the host has lost > max sectors and 1 when the host has lost 0 sectors.

We should also add a way to reset the lost sectors in case a user explicitly wants to forgive a host.

**Comment by peterjan** [comment]
this has been completed
