### ISSUE TITLE
Format the contract spendings in a fiat currency to 2 decimal places

### ISSUE THREAD

**Issue by mike76-dev** [SiaFoundation/renterd#749]
## Describe the bug
The fiat currency values overflow.

## Expected behaviour
The fiat currency values should be formatted to 2 decimal places.

## Additional context
![image](https://github.com/SiaFoundation/renterd/assets/72828450/ae62f73a-3ba3-4ef6-8b1c-031ddca91ee9)

### General Information
Are you running a fork of `renterd`?
Are you on the mainnet or on the testnet?

### Renterd Config
Please provide us the following information:

**Autopilot Config**

```bash
curl -u ":[YOUR_PASSWORD]" http://localhost:9980/api/autopilot/config
```

**Bus Config**

```bash
curl -u ":[YOUR_PASSWORD]" http://localhost:9980/api/bus/setting/redundancy

curl -u ":[YOUR_PASSWORD]" http://localhost:9980/api/bus/setting/gouging
```

**Contract Set Contracts**

```bash
curl -u ":[YOUR_PASSWORD]" http://localhost:9980/api/bus/contracts/set/autopilot | grep '"id"' | wc -l
```

### Renterd Logs
If applicable, upload your `renterd.log` file or part of the file you think is relevant to the issue.

**Comment by peterjan** [comment]
I think this might be an issue still. I'm on latest `master` locally and even with the currency settings flip trick I still get:

<img width="334" alt="Screenshot 2023-12-14 at 10 11 58" src="https://github.com/SiaFoundation/renterd/assets/684818/0e009a02-43af-4b8e-8c39-de9bd982fde8">

**Comment by alexfreska** [comment]
@peterjan do you still see this issue?

**Comment by alexfreska** [comment]
The issue appears to be gone, if you experience it again feel free to re-open.
