### ISSUE TITLE
Transactions Page

### ISSUE THREAD

**Issue by peterjan** [SiaFoundation/renterd#760]
Transactions are ~80MiB causing really low load times when visiting the wallet page.  The route supports various query string parameters to either page or limit the response size to something more manageable. (`since`, `before`, `offset`, `limit`) 

<img width="982" alt="Screenshot 2023-11-23 at 13 08 33" src="https://github.com/SiaFoundation/renterd/assets/684818/6529de70-759c-45e7-b316-23cbc8f2b886">

**Comment by peterjan** [comment]
@alexfreska tagged you on this, hope you don't mind, obviously not urgent but low hanging fruit I guess

**Comment by alexfreska** [comment]
https://github.com/SiaFoundation/web/pull/424

**Comment by peterjan** [comment]
@alexfreska I added wallet metrics <https://github.com/SiaFoundation/renterd/pull/768> I thought you needed that for the graph?

**Comment by peterjan** [comment]
this has been fixed
