### ISSUE TITLE
Correct the redundancy explanation in the UI

### ISSUE THREAD

**Issue by mike76-dev** [SiaFoundation/renterd#810]
### Description

Redundancy is currently explained as the ratio of `min shards / total shards` in the UI, with the default redundancy of 3.0x. However, in the default case (10-of-30) it gives us 0.33x, so it should be the other way around, `total shards / min shards`.
![image](https://github.com/SiaFoundation/renterd/assets/72828450/66679181-6532-4050-a7bc-4a8f76e06157)

**Comment by peterjan** [comment]
fixed
