### ISSUE TITLE
Cannot save config with sector roots pruning disabled

### ISSUE THREAD

**Issue by mike76-dev** [SiaFoundation/renterd#812]
### Current Behavior

The UI considers Prune Sector Roots a required field and doesn't allow saving the config if it is disabled.
![image](https://github.com/SiaFoundation/renterd/assets/72828450/d7bbb7bb-b6a3-46f3-bc1d-878e7f44f854)
![image](https://github.com/SiaFoundation/renterd/assets/72828450/1e7f01e6-0e27-4e66-be8e-fae5f6c68923)

### Expected Behavior

Should be able to save the config regardless.

### Version

Latest `master`

### What operating system did the problem occur on (e.g. Ubuntu 22.04, macOS 12.0, Windows 11)?

Chromium on Ubuntu 22.04

### Autopilot Config

Not relevant

### Bus Config

Not relevant

### Contract Set Contracts

Not relevant

**Comment by peterjan** [comment]
We should probably slightly change the copy too, "old" and "new" hosts is quite vague I think. I would completely drop the part on it being slow on pre 1.6.0 hosts too. Maybe just:


> When enabled, the autopilot will prune deleted sector roots from all contracts. These roots can be safely removed because they where linked to objects that have been deleted, and thus no longer need to be paid for.

**Comment by peterjan** [comment]
fixed
