### ISSUE TITLE
s3: rclone sync is re-uploading already existing files

### ISSUE THREAD

**Issue by artur9010** [SiaFoundation/renterd#833]
### Current Behavior

Probably s3 is not returning all required by rclone to detect duplicate data.
```
2023/12/16 17:06:52 INFO  : logs/2023-10-31-3.log.gz: Copied (replaced existing)
2023/12/16 17:06:52 INFO  : logs/2023-10-31-1.log.gz: Copied (replaced existing)
2023/12/16 17:06:53 INFO  : logs/2023-10-31-2.log.gz: Copied (replaced existing)
2023/12/16 17:06:53 INFO  : logs/2023-10-31-5.log.gz: Copied (replaced existing)
```

after adding --size-only parameter it stopped re-uploading files. I tested it with local and remote s3 as sync source, in both cases it works the same.

https://rclone.org/docs/#size-only
```
--size-only
Normally rclone will look at modification time and size of files to see if they are equal. If you set this flag then rclone will check only the size.

This can be useful transferring files from Dropbox which have been modified by the desktop sync client which doesn't set checksums of modification times in the same way as rclone.
```

### Expected Behavior

Do not reupload existing files

### Version

0.7.1 (zen)

### What operating system did the problem occur on (e.g. Ubuntu 22.04, macOS 12.0, Windows 11)?

Ubuntu 22.04, kubernetes

### Autopilot Config

not necessary

### Bus Config

not necessary

### Contract Set Contracts

not necessary

**Comment by ChrisSchinnerl** [comment]
Quick update on this. It seems the issue is a lack of support for custom metadata on our end. We plan on fixing this as part of releasing custom metadata support for `renterd`.
