### ISSUE TITLE
ui: Overall redundancy stats are unreliable while uploading large files

### ISSUE THREAD

**Issue by artur9010** [SiaFoundation/renterd#834]
### Current Behavior

![image](https://github.com/SiaFoundation/renterd/assets/4835677/6c50f3e6-9611-454e-a005-2baecae9641b)

I run renterd node with 3x redundancy, I'm in progress of uploading some huge files via s3. Overall avg redundancy factor is x12.9.

This probably won't be a problem when hosting large amounts of data, but for smaller instances it could be.

### Expected Behavior

.

### Version

0.7.1 (zen)

### What operating system did the problem occur on (e.g. Ubuntu 22.04, macOS 12.0, Windows 11)?

Ubuntu 22.04, kubernetes

### Autopilot Config

not necessary

### Bus Config

not necessary (probably)

### Contract Set Contracts

not necessary

**Comment by ChrisSchinnerl** [comment]
@alexfreska I think the reason for this is the multipart uploads. I'll extend the `/objects/stats` response to include the total size of unfinished objects as well as the total number of unfinished objects

**Comment by alexfreska** [comment]
Fixed by https://github.com/SiaFoundation/web/releases/tag/renterd%400.42.0
