### ISSUE TITLE
Failed Migration Details

### ISSUE THREAD

**Issue by peterjan** [SiaFoundation/renterd#845]
### Description

use ObjectsBySlabKey to decorate migration failures

### Anything else?

/

**Comment by peterjan** [comment]
I'll remove my assignment until it's moved to TODO (?)

**Comment by ChrisSchinnerl** [comment]
Short term I'd probably list all buckets (shouldn't be too many anyway) and revisit the API design for v2.0.0.
If we only end up using `ObjectsBySlabKey` for migrations we might as well update it to default to all buckets and make the `bucket` param a filter. We can also update the response to already include all the info we want to log/alert.
