### ISSUE TITLE
Add option to sort files/folders by size

### ISSUE THREAD

**Issue by artur9010** [SiaFoundation/renterd#860]
### Description

as in title, there is no option to sort file list by size

### Version

1.0.0-zen

### What operating system are you running (e.g. Ubuntu 22.04, macOS, Windows 11)?

Ubuntu 22.04, kubernetes

**Comment by alexfreska** [comment]
The API currently only supports sorting on `name` and `health`, asc and desc, @peterjan is adding `size` possible?
