### ISSUE TITLE
Paginate alerts or add option to clear without opening them

### ISSUE THREAD

**Issue by artur9010** [SiaFoundation/renterd#862]
### Description

I'm running renterd in kubernetes env, one k8s node that contain worker container went down. I had setup autopilot with remote worker containers, as one of pods weren't available some migrations failed.

![image](https://github.com/SiaFoundation/renterd/assets/4835677/7c746c42-b578-4fa5-b8fe-b770865b4675)

Opening notifications modal with more than 7000 notifications is nearly impossible (chrome will probably kill renterd tab process), there should be a (maybe hidden on bottom of settings?) option to clear them all without opening notification tab.

### Version

1.0.0-zen

### What operating system are you running (e.g. Ubuntu 22.04, macOS, Windows 11)?

Ubuntu 22.04, kubernetes

**Comment by ChrisSchinnerl** [comment]
@alexfreska maybe we need pagination for this? So that opening the alerts doesn't crash the tab

**Comment by alexfreska** [comment]
> @alexfreska maybe we need pagination for this? So that opening the alerts doesn't crash the tab

@ChrisSchinnerl yes I can incorporate pagination if we add it to the endpoint. And also hopefully 7k alerts becomes less common 😅
