### ISSUE TITLE
UI Fails when browsing via port 9880

### ISSUE THREAD

**Issue by capusta** [SiaFoundation/renterd#863]
### Current Behavior

- Run docker compose as per the [instructions](https://github.com/SiaFoundation/renterd#docker-compose)
- configure autopilot with default values
- click save
- UI crash

```
17f6c1eb2e27: Pull complete
05e17398e73f: Pull complete
bb7407992918: Pull complete
Digest: sha256:62feaee81ea3b985a70c58713897bfefa47812b4cd23a95bd615988b51ae8f53
Status: Downloaded newer image for ghcr.io/siafoundation/renterd:master-zen
```

### Expected Behavior

Not crash.

### Steps to Reproduce

1.  start docker compose [via synology nas co[ntainer mana](https://www.synology.com/en-us/dsm/feature/docker)ger]
2. pre-load with test-net faucet
3. browse the internal UI without issues
4. configure autopilot with any default values
5. click save
6. crash

To recover:
1. ssh into docker host
2. delete db folder
3. browser without issues
4. configure any setting on autopilot via UI
5. crash

```
GET
http://10.90.0.0:9880/api/autopilot/config
[HTTP/1.1 404 Not Found 28ms]

XHRGET
http://10.90.0.0:9880/api/bus/setting/contractset
[HTTP/1.1 404 Not Found 22ms]

TypeError: e.wallet is undefined
    NextJS 64
[framework-e151a26869d9e7cc.js:9:69801](http://10.90.0.0:9880/_next/static/chunks/framework-e151a26869d9e7cc.js)
TypeError: e.wallet is undefined
    NextJS 64
[main-e942954303ded134.js:1:10105](http://10.90.0.0:9880/_next/static/chunks/main-e942954303ded134.js)
A client-side exception has occurred, see here for more info: https://nextjs.org/docs/messages/client-side-exception-occurred [main-e942954303ded134.js:1:10122](http://10.90.0.0:9880/_next/static/chunks/main-e942954303ded134.js)
TypeError: e.wallet is undefined
    NextJS 34
[_app-cdfb59ffce05e7b2.js:17:101013](http://10.90.0.0:9880/_next/static/chunks/pages/_app-cdfb59ffce05e7b2.js)
TypeError: e.wallet is undefined
    NextJS 35
[framework-e151a26869d9e7cc.js:9:69801](http://10.90.0.0:9880/_next/static/chunks/framework-e151a26869d9e7cc.js)
TypeError: e.wallet is undefined
    NextJS 35
[main-e942954303ded134.js:1:10105](http://10.90.0.0:9880/_next/static/chunks/main-e942954303ded134.js)
A client-side exception has occurred, see here for more info: https://nextjs.org/docs/messages/client-side-exception-occurred [main-e942954303ded134.js:1:10122](http://10.90.0.0:9880/_next/static/chunks/main-e942954303ded134.js)
```

able to curl the following:

```
curl -u ":test" http://10.90.0.0:9880/api/autopilot/config
{
	"contracts": {
		"set": "autopilot",
		"amount": 12,
		"allowance": "2425226648600000000000000000",
		"period": 6048,
		"renewWindow": 2016,
		"download": 1400000000000,
		"upload": 1400000000000,
		"storage": 1000000000000,
		"prune": false
	},
	"hosts": {
		"allowRedundantIPs": false,
		"maxDowntimeHours": 336,
		"minRecentScanFailures": 10,
		"scoreOverrides": null
	}
}
```
and
```
curl -u ":test" http://10.90.0.0:9880/api/bus/setting/contractset
{
	"default": "autopilot"
}
```

### Version

master-zen

### What operating system did the problem occur on (e.g. Ubuntu 22.04, macOS 12.0, Windows 11)?

n/a (Synology container environment ... so generic docker i guess)

### Autopilot Config

curl -u ":test" http://10.90.0.0:9880/api/autopilot/config { 	"contracts": { 		"set": "autopilot", 		"amount": 12, 		"allowance": "2425226648600000000000000000", 		"period": 6048, 		"renewWindow": 2016, 		"download": 1400000000000, 		"upload": 1400000000000, 		"storage": 1000000000000, 		"prune": false 	}, 	"hosts": { 		"allowRedundantIPs": false, 		"maxDowntimeHours": 336, 		"minRecentScanFailures": 10, 		"scoreOverrides": null 	} }

### Bus Config

curl -u ":test" http://10.90.0.0:9880/api/bus/setting/gouging { 	"hostBlockHeightLeeway": 6, 	"maxContractPrice": "15000000000000000000000000", 	"maxDownloadPrice": "641649380000000000000000000", 	"maxRPCPrice": "1000000000000000000000", 	"maxStoragePrice": "62299451080", 	"maxUploadPrice": "94418161000000000000000000", 	"migrationSurchargeMultiplier": 10, 	"minAccountExpiry": 86400000000000, 	"minMaxCollateral": "10000000000000000000000000", 	"minMaxEphemeralAccountBalance": "1000000000000000000000000", 	"minPriceTableValidity": 300000000000 }

### Contract Set Contracts

curl -u ":test" http://10.90.0.0:9880/api/bus/contracts/set/autopilot Method Not Allowed

### Anything else?

thank you

![image](https://github.com/SiaFoundation/renterd/assets/2278098/b2da817a-2027-48a2-815e-b44261a393d4)

Browser: firefox

**Comment by alexfreska** [comment]
Hey @capusta thank you for the detailed report, could you pull and rebuild `master`, I think this issue should be fixed on the latest - let me know if this does not resolve the issue!

**Comment by capusta** [comment]
latest  zen looks ok
https://github.com/SiaFoundation/renterd/actions/runs/7320257612/job/19939123099#step:8:367
