### ISSUE TITLE
ui: redundancy info should ignore deleted files

### ISSUE THREAD

**Issue by artur9010** [SiaFoundation/renterd#885]
### Current Behavior

after removing a 430GB directory my avg. redundancy went up from 3.2 to 6.7
![image](https://github.com/SiaFoundation/renterd/assets/4835677/ef120fb2-ba7d-4ea5-a17e-4082afc9e26f)

### Expected Behavior

x

### Version

c257679

### What operating system did the problem occur on (e.g. Ubuntu 22.04, macOS 12.0, Windows 11)?

Ubuntu 22.04, kubernetes

### Autopilot Config

not necessary

### Bus Config

not necessary (probably)

### Contract Set Contracts

not necessary

**Comment by ChrisSchinnerl** [comment]
My guess this is not permanent and a result of slabs being pruned asynchronously now. We probably want to extend our object stats with fields that explicitly returns only the size of uploaded sectors which have an associated object.
