### ISSUE TITLE
MigrationSurchargeMultiplier - log file showing a lot of overflow detected

### ISSUE THREAD

**Issue by danielMd2805** [SiaFoundation/renterd#926]
### Current Behavior

During scrolling through the log files of my renterd I found a lot of entries (about 500 a day) with the following message:

`failed to apply the 'MigrationSurchargeMultiplier', overflow detected`

I don't know if it an bug or only a warning message.
Currently I had a lot of files in my renterd where the migration is impossible due missing slabs (9/30).

### Expected Behavior

Currently I don't know what the expected behavior is.

### Version

v1.0.2

### What operating system did the problem occur on (e.g. Ubuntu 22.04, macOS 12.0, Windows 11)?

Ubuntu 22.04

### Autopilot Config

{     "contracts": {         "set": "autopilot",         "amount": 70,         "allowance": "4121975928000000000000000000",         "period": 6048,         "renewWindow": 2016,         "download": 280000000000,         "upload": 700000000000,         "storage": 2200000000000,         "prune": true     },     "hosts": {         "allowRedundantIPs": false,         "maxDowntimeHours": 336,         "minRecentScanFailures": 10,         "scoreOverrides": null     } }

### Bus Config

{     "default": "autopilot" }   {     "hostBlockHeightLeeway": 6,     "maxContractPrice": "1000000000000000000000000",     "maxDownloadPrice": "740910485000000000000000000",     "maxRPCPrice": "1000000000000000000000",     "maxStoragePrice": "71016463040",     "maxUploadPrice": "90176686000000000000000000",     "migrationSurchargeMultiplier": 20,     "minAccountExpiry": 86400000000000,     "minMaxCollateral": "1500000000000000000000000000",     "minMaxEphemeralAccountBalance": "1000000000000000000000000",     "minPriceTableValidity": 300000000000 }  {     "minShards": 10,     "totalShards": 30 }  {     "enabled": true,     "slabBufferMaxSizeSoft": 4294967296 }

### Contract Set Contracts

fcid:df7fcd0c1450817c8395b4464c9728f921099db66b4a0c65613700d63c90230a

**Comment by ChrisSchinnerl** [comment]
@danielMd2805 have you ever updated your gouging settings? More specifically the `migrationSurchargeMultiplier` or `maxDownloadPrice` fields?

The message you are seeing happens when `migrationSurchargeMultiplier * maxDownloadPrice` results in a number that is larger than `128` bits. Looking at the provided settings that should not be the case. So I'm wondering if the settings were higher at some point and you lowered them again?

**Comment by peterjan** [comment]
Fixed in #960
